/* eslint-disable */
// Generated by scripts/gen-china-offline-places.mjs — do not edit by hand.
// Source: src/lib/data/china-pc-code.json (modood/Administrative-divisions-of-China, MIT)
// Regenerate: npm run gen:china-offline

export type OfflineChinaPlaceRow = {
  /** Administrative code (4–6 digits) — stable id fragment */
  code: string;
  zh: string;
  provZh: string;
  /** Latin label for English UI / search (pinyin, no tones) */
  en: string;
  /** Lowercase pinyin concatenation for search / dedupe */
  key: string;
};

export const OFFLINE_CHINA_PLACE_ROWS: readonly OfflineChinaPlaceRow[] = [
  {
    "code": "1302",
    "zh": "唐山市",
    "provZh": "河北省",
    "en": "Tangshan",
    "key": "tangshan"
  },
  {
    "code": "1304",
    "zh": "邯郸市",
    "provZh": "河北省",
    "en": "Handan",
    "key": "handan"
  },
  {
    "code": "1305",
    "zh": "邢台市",
    "provZh": "河北省",
    "en": "Xingtai",
    "key": "xingtai"
  },
  {
    "code": "1306",
    "zh": "保定市",
    "provZh": "河北省",
    "en": "Baoding",
    "key": "baoding"
  },
  {
    "code": "1307",
    "zh": "张家口市",
    "provZh": "河北省",
    "en": "Zhangjiakou",
    "key": "zhangjiakou"
  },
  {
    "code": "1309",
    "zh": "沧州市",
    "provZh": "河北省",
    "en": "Cang",
    "key": "cang"
  },
  {
    "code": "1310",
    "zh": "廊坊市",
    "provZh": "河北省",
    "en": "Langfang",
    "key": "langfang"
  },
  {
    "code": "1311",
    "zh": "衡水市",
    "provZh": "河北省",
    "en": "Hengshui",
    "key": "hengshui"
  },
  {
    "code": "1403",
    "zh": "阳泉市",
    "provZh": "山西省",
    "en": "Yangquan",
    "key": "yangquan"
  },
  {
    "code": "1404",
    "zh": "长治市",
    "provZh": "山西省",
    "en": "Changzhi",
    "key": "changzhi"
  },
  {
    "code": "1405",
    "zh": "晋城市",
    "provZh": "山西省",
    "en": "Jincheng",
    "key": "jincheng"
  },
  {
    "code": "1406",
    "zh": "朔州市",
    "provZh": "山西省",
    "en": "Shuo",
    "key": "shuo"
  },
  {
    "code": "1407",
    "zh": "晋中市",
    "provZh": "山西省",
    "en": "Jinzhong",
    "key": "jinzhong"
  },
  {
    "code": "1408",
    "zh": "运城市",
    "provZh": "山西省",
    "en": "Yuncheng",
    "key": "yuncheng"
  },
  {
    "code": "1409",
    "zh": "忻州市",
    "provZh": "山西省",
    "en": "Xin",
    "key": "xin"
  },
  {
    "code": "1410",
    "zh": "临汾市",
    "provZh": "山西省",
    "en": "Linfen",
    "key": "linfen"
  },
  {
    "code": "1411",
    "zh": "吕梁市",
    "provZh": "山西省",
    "en": "Lüliang",
    "key": "lüliang"
  },
  {
    "code": "1502",
    "zh": "包头市",
    "provZh": "内蒙古自治区",
    "en": "Baotou",
    "key": "baotou"
  },
  {
    "code": "1503",
    "zh": "乌海市",
    "provZh": "内蒙古自治区",
    "en": "Wuhai",
    "key": "wuhai"
  },
  {
    "code": "1504",
    "zh": "赤峰市",
    "provZh": "内蒙古自治区",
    "en": "Chifeng",
    "key": "chifeng"
  },
  {
    "code": "1505",
    "zh": "通辽市",
    "provZh": "内蒙古自治区",
    "en": "Tongliao",
    "key": "tongliao"
  },
  {
    "code": "1507",
    "zh": "呼伦贝尔市",
    "provZh": "内蒙古自治区",
    "en": "Hulunbeier",
    "key": "hulunbeier"
  },
  {
    "code": "1508",
    "zh": "巴彦淖尔市",
    "provZh": "内蒙古自治区",
    "en": "Bayannaoer",
    "key": "bayannaoer"
  },
  {
    "code": "1509",
    "zh": "乌兰察布市",
    "provZh": "内蒙古自治区",
    "en": "Wulanchabu",
    "key": "wulanchabu"
  },
  {
    "code": "1522",
    "zh": "兴安盟",
    "provZh": "内蒙古自治区",
    "en": "Xingan",
    "key": "xingan"
  },
  {
    "code": "1525",
    "zh": "锡林郭勒盟",
    "provZh": "内蒙古自治区",
    "en": "Xilinguole",
    "key": "xilinguole"
  },
  {
    "code": "1529",
    "zh": "阿拉善盟",
    "provZh": "内蒙古自治区",
    "en": "Alashan",
    "key": "alashan"
  },
  {
    "code": "2103",
    "zh": "鞍山市",
    "provZh": "辽宁省",
    "en": "Anshan",
    "key": "anshan"
  },
  {
    "code": "2104",
    "zh": "抚顺市",
    "provZh": "辽宁省",
    "en": "Fushun",
    "key": "fushun"
  },
  {
    "code": "2105",
    "zh": "本溪市",
    "provZh": "辽宁省",
    "en": "Benxi",
    "key": "benxi"
  },
  {
    "code": "2107",
    "zh": "锦州市",
    "provZh": "辽宁省",
    "en": "Jin",
    "key": "jin"
  },
  {
    "code": "2108",
    "zh": "营口市",
    "provZh": "辽宁省",
    "en": "Yingkou",
    "key": "yingkou"
  },
  {
    "code": "2109",
    "zh": "阜新市",
    "provZh": "辽宁省",
    "en": "Fuxin",
    "key": "fuxin"
  },
  {
    "code": "2110",
    "zh": "辽阳市",
    "provZh": "辽宁省",
    "en": "Liaoyang",
    "key": "liaoyang"
  },
  {
    "code": "2111",
    "zh": "盘锦市",
    "provZh": "辽宁省",
    "en": "Panjin",
    "key": "panjin"
  },
  {
    "code": "2112",
    "zh": "铁岭市",
    "provZh": "辽宁省",
    "en": "Tieling",
    "key": "tieling"
  },
  {
    "code": "2113",
    "zh": "朝阳市",
    "provZh": "辽宁省",
    "en": "Chaoyang",
    "key": "chaoyang"
  },
  {
    "code": "2114",
    "zh": "葫芦岛市",
    "provZh": "辽宁省",
    "en": "Huludao",
    "key": "huludao"
  },
  {
    "code": "2202",
    "zh": "吉林市",
    "provZh": "吉林省",
    "en": "Jilin",
    "key": "jilin"
  },
  {
    "code": "2203",
    "zh": "四平市",
    "provZh": "吉林省",
    "en": "Siping",
    "key": "siping"
  },
  {
    "code": "2204",
    "zh": "辽源市",
    "provZh": "吉林省",
    "en": "Liaoyuan",
    "key": "liaoyuan"
  },
  {
    "code": "2205",
    "zh": "通化市",
    "provZh": "吉林省",
    "en": "Tonghua",
    "key": "tonghua"
  },
  {
    "code": "2206",
    "zh": "白山市",
    "provZh": "吉林省",
    "en": "Baishan",
    "key": "baishan"
  },
  {
    "code": "2207",
    "zh": "松原市",
    "provZh": "吉林省",
    "en": "Songyuan",
    "key": "songyuan"
  },
  {
    "code": "2208",
    "zh": "白城市",
    "provZh": "吉林省",
    "en": "Baicheng",
    "key": "baicheng"
  },
  {
    "code": "2224",
    "zh": "延边朝鲜族自治州",
    "provZh": "吉林省",
    "en": "Yanbianchaoxianzuzizhi",
    "key": "yanbianchaoxianzuzizhi"
  },
  {
    "code": "2302",
    "zh": "齐齐哈尔市",
    "provZh": "黑龙江省",
    "en": "Qiqihaer",
    "key": "qiqihaer"
  },
  {
    "code": "2303",
    "zh": "鸡西市",
    "provZh": "黑龙江省",
    "en": "Jixi",
    "key": "jixi"
  },
  {
    "code": "2304",
    "zh": "鹤岗市",
    "provZh": "黑龙江省",
    "en": "Hegang",
    "key": "hegang"
  },
  {
    "code": "2305",
    "zh": "双鸭山市",
    "provZh": "黑龙江省",
    "en": "Shuangyashan",
    "key": "shuangyashan"
  },
  {
    "code": "2306",
    "zh": "大庆市",
    "provZh": "黑龙江省",
    "en": "Daqing",
    "key": "daqing"
  },
  {
    "code": "2307",
    "zh": "伊春市",
    "provZh": "黑龙江省",
    "en": "Yichun",
    "key": "yichun"
  },
  {
    "code": "2308",
    "zh": "佳木斯市",
    "provZh": "黑龙江省",
    "en": "Jiamusi",
    "key": "jiamusi"
  },
  {
    "code": "2309",
    "zh": "七台河市",
    "provZh": "黑龙江省",
    "en": "Qitaihe",
    "key": "qitaihe"
  },
  {
    "code": "2310",
    "zh": "牡丹江市",
    "provZh": "黑龙江省",
    "en": "Mudanjiang",
    "key": "mudanjiang"
  },
  {
    "code": "2311",
    "zh": "黑河市",
    "provZh": "黑龙江省",
    "en": "Heihe",
    "key": "heihe"
  },
  {
    "code": "2312",
    "zh": "绥化市",
    "provZh": "黑龙江省",
    "en": "Suihua",
    "key": "suihua"
  },
  {
    "code": "2327",
    "zh": "大兴安岭地区",
    "provZh": "黑龙江省",
    "en": "Daxinganlingdi",
    "key": "daxinganlingdi"
  },
  {
    "code": "3203",
    "zh": "徐州市",
    "provZh": "江苏省",
    "en": "Xu",
    "key": "xu"
  },
  {
    "code": "3204",
    "zh": "常州市",
    "provZh": "江苏省",
    "en": "Chang",
    "key": "chang"
  },
  {
    "code": "3206",
    "zh": "南通市",
    "provZh": "江苏省",
    "en": "Nantong",
    "key": "nantong"
  },
  {
    "code": "3207",
    "zh": "连云港市",
    "provZh": "江苏省",
    "en": "Lianyungang",
    "key": "lianyungang"
  },
  {
    "code": "3208",
    "zh": "淮安市",
    "provZh": "江苏省",
    "en": "Huaian",
    "key": "huaian"
  },
  {
    "code": "3209",
    "zh": "盐城市",
    "provZh": "江苏省",
    "en": "Yancheng",
    "key": "yancheng"
  },
  {
    "code": "3211",
    "zh": "镇江市",
    "provZh": "江苏省",
    "en": "Zhenjiang",
    "key": "zhenjiang"
  },
  {
    "code": "3212",
    "zh": "泰州市",
    "provZh": "江苏省",
    "en": "Tai",
    "key": "tai"
  },
  {
    "code": "3213",
    "zh": "宿迁市",
    "provZh": "江苏省",
    "en": "Suqian",
    "key": "suqian"
  },
  {
    "code": "3303",
    "zh": "温州市",
    "provZh": "浙江省",
    "en": "Wen",
    "key": "wen"
  },
  {
    "code": "3304",
    "zh": "嘉兴市",
    "provZh": "浙江省",
    "en": "Jiaxing",
    "key": "jiaxing"
  },
  {
    "code": "3305",
    "zh": "湖州市",
    "provZh": "浙江省",
    "en": "Hu",
    "key": "hu"
  },
  {
    "code": "3306",
    "zh": "绍兴市",
    "provZh": "浙江省",
    "en": "Shaoxing",
    "key": "shaoxing"
  },
  {
    "code": "3307",
    "zh": "金华市",
    "provZh": "浙江省",
    "en": "Jinhua",
    "key": "jinhua"
  },
  {
    "code": "3308",
    "zh": "衢州市",
    "provZh": "浙江省",
    "en": "Qu",
    "key": "qu"
  },
  {
    "code": "3310",
    "zh": "台州市",
    "provZh": "浙江省",
    "en": "Tai",
    "key": "tai"
  },
  {
    "code": "3311",
    "zh": "丽水市",
    "provZh": "浙江省",
    "en": "Lishui",
    "key": "lishui"
  },
  {
    "code": "3402",
    "zh": "芜湖市",
    "provZh": "安徽省",
    "en": "Wuhu",
    "key": "wuhu"
  },
  {
    "code": "3403",
    "zh": "蚌埠市",
    "provZh": "安徽省",
    "en": "Bengbu",
    "key": "bengbu"
  },
  {
    "code": "3404",
    "zh": "淮南市",
    "provZh": "安徽省",
    "en": "Huainan",
    "key": "huainan"
  },
  {
    "code": "3405",
    "zh": "马鞍山市",
    "provZh": "安徽省",
    "en": "Maanshan",
    "key": "maanshan"
  },
  {
    "code": "3406",
    "zh": "淮北市",
    "provZh": "安徽省",
    "en": "Huaibei",
    "key": "huaibei"
  },
  {
    "code": "3407",
    "zh": "铜陵市",
    "provZh": "安徽省",
    "en": "Tongling",
    "key": "tongling"
  },
  {
    "code": "3408",
    "zh": "安庆市",
    "provZh": "安徽省",
    "en": "Anqing",
    "key": "anqing"
  },
  {
    "code": "3411",
    "zh": "滁州市",
    "provZh": "安徽省",
    "en": "Chu",
    "key": "chu"
  },
  {
    "code": "3412",
    "zh": "阜阳市",
    "provZh": "安徽省",
    "en": "Fuyang",
    "key": "fuyang"
  },
  {
    "code": "3415",
    "zh": "六安市",
    "provZh": "安徽省",
    "en": "Luan",
    "key": "luan"
  },
  {
    "code": "3416",
    "zh": "亳州市",
    "provZh": "安徽省",
    "en": "Bo",
    "key": "bo"
  },
  {
    "code": "3417",
    "zh": "池州市",
    "provZh": "安徽省",
    "en": "Chi",
    "key": "chi"
  },
  {
    "code": "3418",
    "zh": "宣城市",
    "provZh": "安徽省",
    "en": "Xuancheng",
    "key": "xuancheng"
  },
  {
    "code": "3503",
    "zh": "莆田市",
    "provZh": "福建省",
    "en": "Putian",
    "key": "putian"
  },
  {
    "code": "3504",
    "zh": "三明市",
    "provZh": "福建省",
    "en": "Sanming",
    "key": "sanming"
  },
  {
    "code": "3505",
    "zh": "泉州市",
    "provZh": "福建省",
    "en": "Quan",
    "key": "quan"
  },
  {
    "code": "3506",
    "zh": "漳州市",
    "provZh": "福建省",
    "en": "Zhang",
    "key": "zhang"
  },
  {
    "code": "3507",
    "zh": "南平市",
    "provZh": "福建省",
    "en": "Nanping",
    "key": "nanping"
  },
  {
    "code": "3508",
    "zh": "龙岩市",
    "provZh": "福建省",
    "en": "Longyan",
    "key": "longyan"
  },
  {
    "code": "3509",
    "zh": "宁德市",
    "provZh": "福建省",
    "en": "Ningde",
    "key": "ningde"
  },
  {
    "code": "3603",
    "zh": "萍乡市",
    "provZh": "江西省",
    "en": "Pingxiang",
    "key": "pingxiang"
  },
  {
    "code": "3604",
    "zh": "九江市",
    "provZh": "江西省",
    "en": "Jiujiang",
    "key": "jiujiang"
  },
  {
    "code": "3605",
    "zh": "新余市",
    "provZh": "江西省",
    "en": "Xinyu",
    "key": "xinyu"
  },
  {
    "code": "3606",
    "zh": "鹰潭市",
    "provZh": "江西省",
    "en": "Yingtan",
    "key": "yingtan"
  },
  {
    "code": "3607",
    "zh": "赣州市",
    "provZh": "江西省",
    "en": "Gan",
    "key": "gan"
  },
  {
    "code": "3608",
    "zh": "吉安市",
    "provZh": "江西省",
    "en": "Jian",
    "key": "jian"
  },
  {
    "code": "3609",
    "zh": "宜春市",
    "provZh": "江西省",
    "en": "Yichun",
    "key": "yichun"
  },
  {
    "code": "3611",
    "zh": "上饶市",
    "provZh": "江西省",
    "en": "Shangrao",
    "key": "shangrao"
  },
  {
    "code": "3703",
    "zh": "淄博市",
    "provZh": "山东省",
    "en": "Zibo",
    "key": "zibo"
  },
  {
    "code": "3704",
    "zh": "枣庄市",
    "provZh": "山东省",
    "en": "Zaozhuang",
    "key": "zaozhuang"
  },
  {
    "code": "3705",
    "zh": "东营市",
    "provZh": "山东省",
    "en": "Dongying",
    "key": "dongying"
  },
  {
    "code": "3707",
    "zh": "潍坊市",
    "provZh": "山东省",
    "en": "Weifang",
    "key": "weifang"
  },
  {
    "code": "3708",
    "zh": "济宁市",
    "provZh": "山东省",
    "en": "Jining",
    "key": "jining"
  },
  {
    "code": "3709",
    "zh": "泰安市",
    "provZh": "山东省",
    "en": "Taian",
    "key": "taian"
  },
  {
    "code": "3710",
    "zh": "威海市",
    "provZh": "山东省",
    "en": "Weihai",
    "key": "weihai"
  },
  {
    "code": "3711",
    "zh": "日照市",
    "provZh": "山东省",
    "en": "Rizhao",
    "key": "rizhao"
  },
  {
    "code": "3713",
    "zh": "临沂市",
    "provZh": "山东省",
    "en": "Linyi",
    "key": "linyi"
  },
  {
    "code": "3714",
    "zh": "德州市",
    "provZh": "山东省",
    "en": "De",
    "key": "de"
  },
  {
    "code": "3715",
    "zh": "聊城市",
    "provZh": "山东省",
    "en": "Liaocheng",
    "key": "liaocheng"
  },
  {
    "code": "3716",
    "zh": "滨州市",
    "provZh": "山东省",
    "en": "Bin",
    "key": "bin"
  },
  {
    "code": "3717",
    "zh": "菏泽市",
    "provZh": "山东省",
    "en": "Heze",
    "key": "heze"
  },
  {
    "code": "4104",
    "zh": "平顶山市",
    "provZh": "河南省",
    "en": "Pingdingshan",
    "key": "pingdingshan"
  },
  {
    "code": "4105",
    "zh": "安阳市",
    "provZh": "河南省",
    "en": "Anyang",
    "key": "anyang"
  },
  {
    "code": "4106",
    "zh": "鹤壁市",
    "provZh": "河南省",
    "en": "Hebi",
    "key": "hebi"
  },
  {
    "code": "4107",
    "zh": "新乡市",
    "provZh": "河南省",
    "en": "Xinxiang",
    "key": "xinxiang"
  },
  {
    "code": "4108",
    "zh": "焦作市",
    "provZh": "河南省",
    "en": "Jiaozuo",
    "key": "jiaozuo"
  },
  {
    "code": "4109",
    "zh": "濮阳市",
    "provZh": "河南省",
    "en": "Puyang",
    "key": "puyang"
  },
  {
    "code": "4110",
    "zh": "许昌市",
    "provZh": "河南省",
    "en": "Xuchang",
    "key": "xuchang"
  },
  {
    "code": "4111",
    "zh": "漯河市",
    "provZh": "河南省",
    "en": "Luohe",
    "key": "luohe"
  },
  {
    "code": "4112",
    "zh": "三门峡市",
    "provZh": "河南省",
    "en": "Sanmenxia",
    "key": "sanmenxia"
  },
  {
    "code": "4113",
    "zh": "南阳市",
    "provZh": "河南省",
    "en": "Nanyang",
    "key": "nanyang"
  },
  {
    "code": "4114",
    "zh": "商丘市",
    "provZh": "河南省",
    "en": "Shangqiu",
    "key": "shangqiu"
  },
  {
    "code": "4115",
    "zh": "信阳市",
    "provZh": "河南省",
    "en": "Xinyang",
    "key": "xinyang"
  },
  {
    "code": "4116",
    "zh": "周口市",
    "provZh": "河南省",
    "en": "Zhoukou",
    "key": "zhoukou"
  },
  {
    "code": "4117",
    "zh": "驻马店市",
    "provZh": "河南省",
    "en": "Zhumadian",
    "key": "zhumadian"
  },
  {
    "code": "419001",
    "zh": "济源市",
    "provZh": "河南省",
    "en": "Jiyuan",
    "key": "jiyuan"
  },
  {
    "code": "4202",
    "zh": "黄石市",
    "provZh": "湖北省",
    "en": "Huangshi",
    "key": "huangshi"
  },
  {
    "code": "4203",
    "zh": "十堰市",
    "provZh": "湖北省",
    "en": "Shiyan",
    "key": "shiyan"
  },
  {
    "code": "4206",
    "zh": "襄阳市",
    "provZh": "湖北省",
    "en": "Xiangyang",
    "key": "xiangyang"
  },
  {
    "code": "4207",
    "zh": "鄂州市",
    "provZh": "湖北省",
    "en": "E",
    "key": "e"
  },
  {
    "code": "4208",
    "zh": "荆门市",
    "provZh": "湖北省",
    "en": "Jingmen",
    "key": "jingmen"
  },
  {
    "code": "4209",
    "zh": "孝感市",
    "provZh": "湖北省",
    "en": "Xiaogan",
    "key": "xiaogan"
  },
  {
    "code": "4210",
    "zh": "荆州市",
    "provZh": "湖北省",
    "en": "Jing",
    "key": "jing"
  },
  {
    "code": "4211",
    "zh": "黄冈市",
    "provZh": "湖北省",
    "en": "Huanggang",
    "key": "huanggang"
  },
  {
    "code": "4212",
    "zh": "咸宁市",
    "provZh": "湖北省",
    "en": "Xianning",
    "key": "xianning"
  },
  {
    "code": "4213",
    "zh": "随州市",
    "provZh": "湖北省",
    "en": "Sui",
    "key": "sui"
  },
  {
    "code": "4228",
    "zh": "恩施土家族苗族自治州",
    "provZh": "湖北省",
    "en": "Enshitujiazumiaozuzizhi",
    "key": "enshitujiazumiaozuzizhi"
  },
  {
    "code": "429004",
    "zh": "仙桃市",
    "provZh": "湖北省",
    "en": "Xiantao",
    "key": "xiantao"
  },
  {
    "code": "429005",
    "zh": "潜江市",
    "provZh": "湖北省",
    "en": "Qianjiang",
    "key": "qianjiang"
  },
  {
    "code": "429006",
    "zh": "天门市",
    "provZh": "湖北省",
    "en": "Tianmen",
    "key": "tianmen"
  },
  {
    "code": "429021",
    "zh": "神农架林区",
    "provZh": "湖北省",
    "en": "Shennongjialin",
    "key": "shennongjialin"
  },
  {
    "code": "4302",
    "zh": "株洲市",
    "provZh": "湖南省",
    "en": "Zhuzhou",
    "key": "zhuzhou"
  },
  {
    "code": "4303",
    "zh": "湘潭市",
    "provZh": "湖南省",
    "en": "Xiangtan",
    "key": "xiangtan"
  },
  {
    "code": "4304",
    "zh": "衡阳市",
    "provZh": "湖南省",
    "en": "Hengyang",
    "key": "hengyang"
  },
  {
    "code": "4305",
    "zh": "邵阳市",
    "provZh": "湖南省",
    "en": "Shaoyang",
    "key": "shaoyang"
  },
  {
    "code": "4306",
    "zh": "岳阳市",
    "provZh": "湖南省",
    "en": "Yueyang",
    "key": "yueyang"
  },
  {
    "code": "4307",
    "zh": "常德市",
    "provZh": "湖南省",
    "en": "Changde",
    "key": "changde"
  },
  {
    "code": "4309",
    "zh": "益阳市",
    "provZh": "湖南省",
    "en": "Yiyang",
    "key": "yiyang"
  },
  {
    "code": "4310",
    "zh": "郴州市",
    "provZh": "湖南省",
    "en": "Chen",
    "key": "chen"
  },
  {
    "code": "4311",
    "zh": "永州市",
    "provZh": "湖南省",
    "en": "Yong",
    "key": "yong"
  },
  {
    "code": "4312",
    "zh": "怀化市",
    "provZh": "湖南省",
    "en": "Huaihua",
    "key": "huaihua"
  },
  {
    "code": "4313",
    "zh": "娄底市",
    "provZh": "湖南省",
    "en": "Loudi",
    "key": "loudi"
  },
  {
    "code": "4331",
    "zh": "湘西土家族苗族自治州",
    "provZh": "湖南省",
    "en": "Xiangxitujiazumiaozuzizhi",
    "key": "xiangxitujiazumiaozuzizhi"
  },
  {
    "code": "4402",
    "zh": "韶关市",
    "provZh": "广东省",
    "en": "Shaoguan",
    "key": "shaoguan"
  },
  {
    "code": "4405",
    "zh": "汕头市",
    "provZh": "广东省",
    "en": "Shantou",
    "key": "shantou"
  },
  {
    "code": "4406",
    "zh": "佛山市",
    "provZh": "广东省",
    "en": "Foshan",
    "key": "foshan"
  },
  {
    "code": "4407",
    "zh": "江门市",
    "provZh": "广东省",
    "en": "Jiangmen",
    "key": "jiangmen"
  },
  {
    "code": "4408",
    "zh": "湛江市",
    "provZh": "广东省",
    "en": "Zhanjiang",
    "key": "zhanjiang"
  },
  {
    "code": "4409",
    "zh": "茂名市",
    "provZh": "广东省",
    "en": "Maoming",
    "key": "maoming"
  },
  {
    "code": "4412",
    "zh": "肇庆市",
    "provZh": "广东省",
    "en": "Zhaoqing",
    "key": "zhaoqing"
  },
  {
    "code": "4413",
    "zh": "惠州市",
    "provZh": "广东省",
    "en": "Hui",
    "key": "hui"
  },
  {
    "code": "4414",
    "zh": "梅州市",
    "provZh": "广东省",
    "en": "Mei",
    "key": "mei"
  },
  {
    "code": "4415",
    "zh": "汕尾市",
    "provZh": "广东省",
    "en": "Shanwei",
    "key": "shanwei"
  },
  {
    "code": "4416",
    "zh": "河源市",
    "provZh": "广东省",
    "en": "Heyuan",
    "key": "heyuan"
  },
  {
    "code": "4417",
    "zh": "阳江市",
    "provZh": "广东省",
    "en": "Yangjiang",
    "key": "yangjiang"
  },
  {
    "code": "4418",
    "zh": "清远市",
    "provZh": "广东省",
    "en": "Qingyuan",
    "key": "qingyuan"
  },
  {
    "code": "4419",
    "zh": "东莞市",
    "provZh": "广东省",
    "en": "Dongguan",
    "key": "dongguan"
  },
  {
    "code": "4420",
    "zh": "中山市",
    "provZh": "广东省",
    "en": "Zhongshan",
    "key": "zhongshan"
  },
  {
    "code": "4451",
    "zh": "潮州市",
    "provZh": "广东省",
    "en": "Chao",
    "key": "chao"
  },
  {
    "code": "4452",
    "zh": "揭阳市",
    "provZh": "广东省",
    "en": "Jieyang",
    "key": "jieyang"
  },
  {
    "code": "4453",
    "zh": "云浮市",
    "provZh": "广东省",
    "en": "Yunfu",
    "key": "yunfu"
  },
  {
    "code": "4502",
    "zh": "柳州市",
    "provZh": "广西壮族自治区",
    "en": "Liu",
    "key": "liu"
  },
  {
    "code": "4504",
    "zh": "梧州市",
    "provZh": "广西壮族自治区",
    "en": "Wu",
    "key": "wu"
  },
  {
    "code": "4505",
    "zh": "北海市",
    "provZh": "广西壮族自治区",
    "en": "Beihai",
    "key": "beihai"
  },
  {
    "code": "4506",
    "zh": "防城港市",
    "provZh": "广西壮族自治区",
    "en": "Fangchenggang",
    "key": "fangchenggang"
  },
  {
    "code": "4507",
    "zh": "钦州市",
    "provZh": "广西壮族自治区",
    "en": "Qin",
    "key": "qin"
  },
  {
    "code": "4508",
    "zh": "贵港市",
    "provZh": "广西壮族自治区",
    "en": "Guigang",
    "key": "guigang"
  },
  {
    "code": "4509",
    "zh": "玉林市",
    "provZh": "广西壮族自治区",
    "en": "Yulin",
    "key": "yulin"
  },
  {
    "code": "4510",
    "zh": "百色市",
    "provZh": "广西壮族自治区",
    "en": "Baise",
    "key": "baise"
  },
  {
    "code": "4511",
    "zh": "贺州市",
    "provZh": "广西壮族自治区",
    "en": "He",
    "key": "he"
  },
  {
    "code": "4512",
    "zh": "河池市",
    "provZh": "广西壮族自治区",
    "en": "Hechi",
    "key": "hechi"
  },
  {
    "code": "4513",
    "zh": "来宾市",
    "provZh": "广西壮族自治区",
    "en": "Laibin",
    "key": "laibin"
  },
  {
    "code": "4514",
    "zh": "崇左市",
    "provZh": "广西壮族自治区",
    "en": "Chongzuo",
    "key": "chongzuo"
  },
  {
    "code": "4603",
    "zh": "三沙市",
    "provZh": "海南省",
    "en": "Sansha",
    "key": "sansha"
  },
  {
    "code": "4604",
    "zh": "儋州市",
    "provZh": "海南省",
    "en": "Dan",
    "key": "dan"
  },
  {
    "code": "469001",
    "zh": "五指山市",
    "provZh": "海南省",
    "en": "Wuzhishan",
    "key": "wuzhishan"
  },
  {
    "code": "469002",
    "zh": "琼海市",
    "provZh": "海南省",
    "en": "Qionghai",
    "key": "qionghai"
  },
  {
    "code": "469005",
    "zh": "文昌市",
    "provZh": "海南省",
    "en": "Wenchang",
    "key": "wenchang"
  },
  {
    "code": "469006",
    "zh": "万宁市",
    "provZh": "海南省",
    "en": "Wanning",
    "key": "wanning"
  },
  {
    "code": "469007",
    "zh": "东方市",
    "provZh": "海南省",
    "en": "Dongfang",
    "key": "dongfang"
  },
  {
    "code": "469021",
    "zh": "定安县",
    "provZh": "海南省",
    "en": "Dingan",
    "key": "dingan"
  },
  {
    "code": "469022",
    "zh": "屯昌县",
    "provZh": "海南省",
    "en": "Tunchang",
    "key": "tunchang"
  },
  {
    "code": "469023",
    "zh": "澄迈县",
    "provZh": "海南省",
    "en": "Chengmai",
    "key": "chengmai"
  },
  {
    "code": "469024",
    "zh": "临高县",
    "provZh": "海南省",
    "en": "Lingao",
    "key": "lingao"
  },
  {
    "code": "469025",
    "zh": "白沙黎族自治县",
    "provZh": "海南省",
    "en": "Baishalizuzizhi",
    "key": "baishalizuzizhi"
  },
  {
    "code": "469026",
    "zh": "昌江黎族自治县",
    "provZh": "海南省",
    "en": "Changjianglizuzizhi",
    "key": "changjianglizuzizhi"
  },
  {
    "code": "469027",
    "zh": "乐东黎族自治县",
    "provZh": "海南省",
    "en": "Ledonglizuzizhi",
    "key": "ledonglizuzizhi"
  },
  {
    "code": "469028",
    "zh": "陵水黎族自治县",
    "provZh": "海南省",
    "en": "Lingshuilizuzizhi",
    "key": "lingshuilizuzizhi"
  },
  {
    "code": "469029",
    "zh": "保亭黎族苗族自治县",
    "provZh": "海南省",
    "en": "Baotinglizumiaozuzizhi",
    "key": "baotinglizumiaozuzizhi"
  },
  {
    "code": "469030",
    "zh": "琼中黎族苗族自治县",
    "provZh": "海南省",
    "en": "Qiongzhonglizumiaozuzizhi",
    "key": "qiongzhonglizumiaozuzizhi"
  },
  {
    "code": "5103",
    "zh": "自贡市",
    "provZh": "四川省",
    "en": "Zigong",
    "key": "zigong"
  },
  {
    "code": "5104",
    "zh": "攀枝花市",
    "provZh": "四川省",
    "en": "Panzhihua",
    "key": "panzhihua"
  },
  {
    "code": "5105",
    "zh": "泸州市",
    "provZh": "四川省",
    "en": "Lu",
    "key": "lu"
  },
  {
    "code": "5106",
    "zh": "德阳市",
    "provZh": "四川省",
    "en": "Deyang",
    "key": "deyang"
  },
  {
    "code": "5107",
    "zh": "绵阳市",
    "provZh": "四川省",
    "en": "Mianyang",
    "key": "mianyang"
  },
  {
    "code": "5108",
    "zh": "广元市",
    "provZh": "四川省",
    "en": "Guangyuan",
    "key": "guangyuan"
  },
  {
    "code": "5109",
    "zh": "遂宁市",
    "provZh": "四川省",
    "en": "Suining",
    "key": "suining"
  },
  {
    "code": "5110",
    "zh": "内江市",
    "provZh": "四川省",
    "en": "Neijiang",
    "key": "neijiang"
  },
  {
    "code": "5113",
    "zh": "南充市",
    "provZh": "四川省",
    "en": "Nanchong",
    "key": "nanchong"
  },
  {
    "code": "5114",
    "zh": "眉山市",
    "provZh": "四川省",
    "en": "Meishan",
    "key": "meishan"
  },
  {
    "code": "5115",
    "zh": "宜宾市",
    "provZh": "四川省",
    "en": "Yibin",
    "key": "yibin"
  },
  {
    "code": "5116",
    "zh": "广安市",
    "provZh": "四川省",
    "en": "Guangan",
    "key": "guangan"
  },
  {
    "code": "5117",
    "zh": "达州市",
    "provZh": "四川省",
    "en": "Da",
    "key": "da"
  },
  {
    "code": "5118",
    "zh": "雅安市",
    "provZh": "四川省",
    "en": "Yaan",
    "key": "yaan"
  },
  {
    "code": "5119",
    "zh": "巴中市",
    "provZh": "四川省",
    "en": "Bazhong",
    "key": "bazhong"
  },
  {
    "code": "5120",
    "zh": "资阳市",
    "provZh": "四川省",
    "en": "Ziyang",
    "key": "ziyang"
  },
  {
    "code": "5132",
    "zh": "阿坝藏族羌族自治州",
    "provZh": "四川省",
    "en": "Abazangzuqiangzuzizhi",
    "key": "abazangzuqiangzuzizhi"
  },
  {
    "code": "5133",
    "zh": "甘孜藏族自治州",
    "provZh": "四川省",
    "en": "Ganzizangzuzizhi",
    "key": "ganzizangzuzizhi"
  },
  {
    "code": "5134",
    "zh": "凉山彝族自治州",
    "provZh": "四川省",
    "en": "Liangshanyizuzizhi",
    "key": "liangshanyizuzizhi"
  },
  {
    "code": "5202",
    "zh": "六盘水市",
    "provZh": "贵州省",
    "en": "Liupanshui",
    "key": "liupanshui"
  },
  {
    "code": "5203",
    "zh": "遵义市",
    "provZh": "贵州省",
    "en": "Zunyi",
    "key": "zunyi"
  },
  {
    "code": "5204",
    "zh": "安顺市",
    "provZh": "贵州省",
    "en": "Anshun",
    "key": "anshun"
  },
  {
    "code": "5205",
    "zh": "毕节市",
    "provZh": "贵州省",
    "en": "Bijie",
    "key": "bijie"
  },
  {
    "code": "5206",
    "zh": "铜仁市",
    "provZh": "贵州省",
    "en": "Tongren",
    "key": "tongren"
  },
  {
    "code": "5223",
    "zh": "黔西南布依族苗族自治州",
    "provZh": "贵州省",
    "en": "Qianxinanbuyizumiaozuzizhi",
    "key": "qianxinanbuyizumiaozuzizhi"
  },
  {
    "code": "5226",
    "zh": "黔东南苗族侗族自治州",
    "provZh": "贵州省",
    "en": "Qiandongnanmiaozudongzuzizhi",
    "key": "qiandongnanmiaozudongzuzizhi"
  },
  {
    "code": "5227",
    "zh": "黔南布依族苗族自治州",
    "provZh": "贵州省",
    "en": "Qiannanbuyizumiaozuzizhi",
    "key": "qiannanbuyizumiaozuzizhi"
  },
  {
    "code": "5303",
    "zh": "曲靖市",
    "provZh": "云南省",
    "en": "Qujing",
    "key": "qujing"
  },
  {
    "code": "5304",
    "zh": "玉溪市",
    "provZh": "云南省",
    "en": "Yuxi",
    "key": "yuxi"
  },
  {
    "code": "5305",
    "zh": "保山市",
    "provZh": "云南省",
    "en": "Baoshan",
    "key": "baoshan"
  },
  {
    "code": "5306",
    "zh": "昭通市",
    "provZh": "云南省",
    "en": "Zhaotong",
    "key": "zhaotong"
  },
  {
    "code": "5308",
    "zh": "普洱市",
    "provZh": "云南省",
    "en": "Puer",
    "key": "puer"
  },
  {
    "code": "5309",
    "zh": "临沧市",
    "provZh": "云南省",
    "en": "Lincang",
    "key": "lincang"
  },
  {
    "code": "5323",
    "zh": "楚雄彝族自治州",
    "provZh": "云南省",
    "en": "Chuxiongyizuzizhi",
    "key": "chuxiongyizuzizhi"
  },
  {
    "code": "5325",
    "zh": "红河哈尼族彝族自治州",
    "provZh": "云南省",
    "en": "Honghehanizuyizuzizhi",
    "key": "honghehanizuyizuzizhi"
  },
  {
    "code": "5326",
    "zh": "文山壮族苗族自治州",
    "provZh": "云南省",
    "en": "Wenshanzhuangzumiaozuzizhi",
    "key": "wenshanzhuangzumiaozuzizhi"
  },
  {
    "code": "5328",
    "zh": "西双版纳傣族自治州",
    "provZh": "云南省",
    "en": "Xishuangbannadaizuzizhi",
    "key": "xishuangbannadaizuzizhi"
  },
  {
    "code": "5329",
    "zh": "大理白族自治州",
    "provZh": "云南省",
    "en": "Dalibaizuzizhi",
    "key": "dalibaizuzizhi"
  },
  {
    "code": "5331",
    "zh": "德宏傣族景颇族自治州",
    "provZh": "云南省",
    "en": "Dehongdaizujingpozuzizhi",
    "key": "dehongdaizujingpozuzizhi"
  },
  {
    "code": "5333",
    "zh": "怒江傈僳族自治州",
    "provZh": "云南省",
    "en": "Nujianglisuzuzizhi",
    "key": "nujianglisuzuzizhi"
  },
  {
    "code": "5334",
    "zh": "迪庆藏族自治州",
    "provZh": "云南省",
    "en": "Diqingzangzuzizhi",
    "key": "diqingzangzuzizhi"
  },
  {
    "code": "5403",
    "zh": "昌都市",
    "provZh": "西藏自治区",
    "en": "Changdou",
    "key": "changdou"
  },
  {
    "code": "5404",
    "zh": "林芝市",
    "provZh": "西藏自治区",
    "en": "Linzhi",
    "key": "linzhi"
  },
  {
    "code": "5405",
    "zh": "山南市",
    "provZh": "西藏自治区",
    "en": "Shannan",
    "key": "shannan"
  },
  {
    "code": "5406",
    "zh": "那曲市",
    "provZh": "西藏自治区",
    "en": "Naqu",
    "key": "naqu"
  },
  {
    "code": "5425",
    "zh": "阿里地区",
    "provZh": "西藏自治区",
    "en": "Alidi",
    "key": "alidi"
  },
  {
    "code": "6102",
    "zh": "铜川市",
    "provZh": "陕西省",
    "en": "Tongchuan",
    "key": "tongchuan"
  },
  {
    "code": "6103",
    "zh": "宝鸡市",
    "provZh": "陕西省",
    "en": "Baoji",
    "key": "baoji"
  },
  {
    "code": "6104",
    "zh": "咸阳市",
    "provZh": "陕西省",
    "en": "Xianyang",
    "key": "xianyang"
  },
  {
    "code": "6105",
    "zh": "渭南市",
    "provZh": "陕西省",
    "en": "Weinan",
    "key": "weinan"
  },
  {
    "code": "6106",
    "zh": "延安市",
    "provZh": "陕西省",
    "en": "Yanan",
    "key": "yanan"
  },
  {
    "code": "6107",
    "zh": "汉中市",
    "provZh": "陕西省",
    "en": "Hanzhong",
    "key": "hanzhong"
  },
  {
    "code": "6108",
    "zh": "榆林市",
    "provZh": "陕西省",
    "en": "Yulin",
    "key": "yulin"
  },
  {
    "code": "6109",
    "zh": "安康市",
    "provZh": "陕西省",
    "en": "Ankang",
    "key": "ankang"
  },
  {
    "code": "6110",
    "zh": "商洛市",
    "provZh": "陕西省",
    "en": "Shangluo",
    "key": "shangluo"
  },
  {
    "code": "6202",
    "zh": "嘉峪关市",
    "provZh": "甘肃省",
    "en": "Jiayuguan",
    "key": "jiayuguan"
  },
  {
    "code": "6203",
    "zh": "金昌市",
    "provZh": "甘肃省",
    "en": "Jinchang",
    "key": "jinchang"
  },
  {
    "code": "6204",
    "zh": "白银市",
    "provZh": "甘肃省",
    "en": "Baiyin",
    "key": "baiyin"
  },
  {
    "code": "6205",
    "zh": "天水市",
    "provZh": "甘肃省",
    "en": "Tianshui",
    "key": "tianshui"
  },
  {
    "code": "6206",
    "zh": "武威市",
    "provZh": "甘肃省",
    "en": "Wuwei",
    "key": "wuwei"
  },
  {
    "code": "6207",
    "zh": "张掖市",
    "provZh": "甘肃省",
    "en": "Zhangye",
    "key": "zhangye"
  },
  {
    "code": "6208",
    "zh": "平凉市",
    "provZh": "甘肃省",
    "en": "Pingliang",
    "key": "pingliang"
  },
  {
    "code": "6209",
    "zh": "酒泉市",
    "provZh": "甘肃省",
    "en": "Jiuquan",
    "key": "jiuquan"
  },
  {
    "code": "6210",
    "zh": "庆阳市",
    "provZh": "甘肃省",
    "en": "Qingyang",
    "key": "qingyang"
  },
  {
    "code": "6211",
    "zh": "定西市",
    "provZh": "甘肃省",
    "en": "Dingxi",
    "key": "dingxi"
  },
  {
    "code": "6212",
    "zh": "陇南市",
    "provZh": "甘肃省",
    "en": "Longnan",
    "key": "longnan"
  },
  {
    "code": "6229",
    "zh": "临夏回族自治州",
    "provZh": "甘肃省",
    "en": "Linxiahuizuzizhi",
    "key": "linxiahuizuzizhi"
  },
  {
    "code": "6230",
    "zh": "甘南藏族自治州",
    "provZh": "甘肃省",
    "en": "Gannanzangzuzizhi",
    "key": "gannanzangzuzizhi"
  },
  {
    "code": "6302",
    "zh": "海东市",
    "provZh": "青海省",
    "en": "Haidong",
    "key": "haidong"
  },
  {
    "code": "6322",
    "zh": "海北藏族自治州",
    "provZh": "青海省",
    "en": "Haibeizangzuzizhi",
    "key": "haibeizangzuzizhi"
  },
  {
    "code": "6323",
    "zh": "黄南藏族自治州",
    "provZh": "青海省",
    "en": "Huangnanzangzuzizhi",
    "key": "huangnanzangzuzizhi"
  },
  {
    "code": "6325",
    "zh": "海南藏族自治州",
    "provZh": "青海省",
    "en": "Hainanzangzuzizhi",
    "key": "hainanzangzuzizhi"
  },
  {
    "code": "6326",
    "zh": "果洛藏族自治州",
    "provZh": "青海省",
    "en": "Guoluozangzuzizhi",
    "key": "guoluozangzuzizhi"
  },
  {
    "code": "6327",
    "zh": "玉树藏族自治州",
    "provZh": "青海省",
    "en": "Yushuzangzuzizhi",
    "key": "yushuzangzuzizhi"
  },
  {
    "code": "6328",
    "zh": "海西蒙古族藏族自治州",
    "provZh": "青海省",
    "en": "Haiximengguzuzangzuzizhi",
    "key": "haiximengguzuzangzuzizhi"
  },
  {
    "code": "6402",
    "zh": "石嘴山市",
    "provZh": "宁夏回族自治区",
    "en": "Shizuishan",
    "key": "shizuishan"
  },
  {
    "code": "6403",
    "zh": "吴忠市",
    "provZh": "宁夏回族自治区",
    "en": "Wuzhong",
    "key": "wuzhong"
  },
  {
    "code": "6404",
    "zh": "固原市",
    "provZh": "宁夏回族自治区",
    "en": "Guyuan",
    "key": "guyuan"
  },
  {
    "code": "6405",
    "zh": "中卫市",
    "provZh": "宁夏回族自治区",
    "en": "Zhongwei",
    "key": "zhongwei"
  },
  {
    "code": "6502",
    "zh": "克拉玛依市",
    "provZh": "新疆维吾尔自治区",
    "en": "Kelamayi",
    "key": "kelamayi"
  },
  {
    "code": "6504",
    "zh": "吐鲁番市",
    "provZh": "新疆维吾尔自治区",
    "en": "Tulufan",
    "key": "tulufan"
  },
  {
    "code": "6505",
    "zh": "哈密市",
    "provZh": "新疆维吾尔自治区",
    "en": "Hami",
    "key": "hami"
  },
  {
    "code": "6523",
    "zh": "昌吉回族自治州",
    "provZh": "新疆维吾尔自治区",
    "en": "Changjihuizuzizhi",
    "key": "changjihuizuzizhi"
  },
  {
    "code": "6527",
    "zh": "博尔塔拉蒙古自治州",
    "provZh": "新疆维吾尔自治区",
    "en": "Boertalamengguzizhi",
    "key": "boertalamengguzizhi"
  },
  {
    "code": "6528",
    "zh": "巴音郭楞蒙古自治州",
    "provZh": "新疆维吾尔自治区",
    "en": "Bayinguolengmengguzizhi",
    "key": "bayinguolengmengguzizhi"
  },
  {
    "code": "6529",
    "zh": "阿克苏地区",
    "provZh": "新疆维吾尔自治区",
    "en": "Akesudi",
    "key": "akesudi"
  },
  {
    "code": "6530",
    "zh": "克孜勒苏柯尔克孜自治州",
    "provZh": "新疆维吾尔自治区",
    "en": "Kezilesukeerkezizizhi",
    "key": "kezilesukeerkezizizhi"
  },
  {
    "code": "6531",
    "zh": "喀什地区",
    "provZh": "新疆维吾尔自治区",
    "en": "Kashendi",
    "key": "kashendi"
  },
  {
    "code": "6532",
    "zh": "和田地区",
    "provZh": "新疆维吾尔自治区",
    "en": "Hetiandi",
    "key": "hetiandi"
  },
  {
    "code": "6540",
    "zh": "伊犁哈萨克自治州",
    "provZh": "新疆维吾尔自治区",
    "en": "Yilihasakezizhi",
    "key": "yilihasakezizhi"
  },
  {
    "code": "6542",
    "zh": "塔城地区",
    "provZh": "新疆维吾尔自治区",
    "en": "Tachengdi",
    "key": "tachengdi"
  },
  {
    "code": "6543",
    "zh": "阿勒泰地区",
    "provZh": "新疆维吾尔自治区",
    "en": "Aletaidi",
    "key": "aletaidi"
  },
  {
    "code": "659001",
    "zh": "石河子市",
    "provZh": "新疆维吾尔自治区",
    "en": "Shihezi",
    "key": "shihezi"
  },
  {
    "code": "659002",
    "zh": "阿拉尔市",
    "provZh": "新疆维吾尔自治区",
    "en": "Alaer",
    "key": "alaer"
  },
  {
    "code": "659003",
    "zh": "图木舒克市",
    "provZh": "新疆维吾尔自治区",
    "en": "Tumushuke",
    "key": "tumushuke"
  },
  {
    "code": "659004",
    "zh": "五家渠市",
    "provZh": "新疆维吾尔自治区",
    "en": "Wujiaqu",
    "key": "wujiaqu"
  },
  {
    "code": "659005",
    "zh": "北屯市",
    "provZh": "新疆维吾尔自治区",
    "en": "Beitun",
    "key": "beitun"
  },
  {
    "code": "659006",
    "zh": "铁门关市",
    "provZh": "新疆维吾尔自治区",
    "en": "Tiemenguan",
    "key": "tiemenguan"
  },
  {
    "code": "659007",
    "zh": "双河市",
    "provZh": "新疆维吾尔自治区",
    "en": "Shuanghe",
    "key": "shuanghe"
  },
  {
    "code": "659008",
    "zh": "可克达拉市",
    "provZh": "新疆维吾尔自治区",
    "en": "Kekedala",
    "key": "kekedala"
  },
  {
    "code": "659009",
    "zh": "昆玉市",
    "provZh": "新疆维吾尔自治区",
    "en": "Kunyu",
    "key": "kunyu"
  },
  {
    "code": "659010",
    "zh": "胡杨河市",
    "provZh": "新疆维吾尔自治区",
    "en": "Huyanghe",
    "key": "huyanghe"
  },
  {
    "code": "659011",
    "zh": "新星市",
    "provZh": "新疆维吾尔自治区",
    "en": "Xinxing",
    "key": "xinxing"
  },
  {
    "code": "659012",
    "zh": "白杨市",
    "provZh": "新疆维吾尔自治区",
    "en": "Baiyang",
    "key": "baiyang"
  }
] as const;
