import type { CommunityItem, CommunityTemplate } from "./packlog-data";

const BIG3_EN = [
  "## What people mean by **Big 3**",
  "",
  "In backpacking communities, *Big 3* usually refers to the three weight columns that dominate a spreadsheet:",
  "",
  "1. **Shelter** — tent, tarp, hammock setup, or bivy you sleep under.",
  "2. **Sleep system** — quilt or sleeping bag, sleeping pad, and sometimes pillow.",
  "3. **Carry** — the backpack itself (plus frame / hipbelt if counted separately).",
  "",
  "### Why it matters",
  "",
  "Together these categories are often **40–60%** of *base pack weight* (before food, water, and fuel). Saving grams here has more leverage than chasing marginal gains on small accessories.",
  "",
  "### Not a rule",
  "",
  "Desert fast-packs, winter traverses, and family car camping do not share the same answers. Treat Big 3 as a **thinking tool**, not a checklist you must tick literally.",
  "",
  "### Rows below",
  "",
  "The attached rows are **illustrative mid-weight examples** — clone them into a trip, then edit names, weights, and categories to match your real kit.",
].join("\n");

const BIG3_ZH = [
  "## 「Big 3 / 三大件」一般指什么？",
  "",
  "在徒步社区里，**Big 3** 通常指表格里最占重量的三列：",
  "",
  "1. **庇护所** — 帐篷、天幕、吊床系统或 bivy。",
  "2. **睡眠系统** — 睡袋/睡被、睡垫，有时含枕头。",
  "3. **背负** — 背包本体（若单独统计框架/腰带可自行调整口径）。",
  "",
  "### 为什么老提它",
  "",
  "这三块常常占到 **基础背包重量**（不含路餐、水、燃料）的 **40–60%**。在这里抠克数，通常比在配件上纠结收益更高。",
  "",
  "### 不是教条",
  "",
  "沙漠速穿、冬季长线与亲子自驾露营，答案不会一样。把 Big 3 当成 **思考框架**，而不是必须逐字照抄的清单。",
  "",
  "### 下方示例行",
  "",
  "附带的几行是 **示意性的中等重量示例** — 克隆到行程后请按你的真实装备改名、改克数与类别。",
].join("\n");

const UL_EN = [
  "## Ultralight backpacking — a practical intro",
  "",
  "### What “ultralight” usually implies",
  "",
  "- **Base weight** targets (very rough): many weekend hikers aim near **~4.5–7kg** base in warm 3-season weather; lower is possible with experience and narrower safety margins.",
  "- **Multi-use gear** — one item doing two jobs (e.g. trekking poles + tarp pitch).",
  "- **Smaller safety buffer** — you carry less redundancy; that demands better skills, forecasts, and bail-out plans.",
  "",
  "### Trade-offs (be honest)",
  "",
  "| Gain | Cost |",
  "| --- | --- |",
  "| Less mass on back | Less margin for cold / injury / delay |",
  "| Faster miles | Fewer “just in case” comforts |",
  "| Simpler kit | More skill required to stay safe |",
  "",
  "### Where to start",
  "",
  "1. Weigh everything you already carry (kitchen scale + spreadsheet).",
  "2. Attack **Big 3** and **packed clothing** first.",
  "3. Never skip **navigation, insulation, rain, first aid, repair, fire/light** appropriate to your route — adapt the *Ten Essentials* to context.",
  "",
  "### Attached rows",
  "",
  "Example **starter lines** you can merge into a trip; adjust every number before trusting it in the field.",
].join("\n");

const UL_ZH = [
  "## 超轻徒步（Ultralight）入门：务实版",
  "",
  "### 通常意味着什么",
  "",
  "- **基础重量**（很粗略）：暖季三日左右，常见目标区间大概在 **~4.5–7kg** 基础重量；经验更足、风险承受更高的人可以更低。",
  "- **一物多用** — 例如登山杖兼做天幕支撑。",
  "- **冗余更小** — 更少「以防万一」；需要更好的天气判断、路线能力与下撤方案。",
  "",
  "### 取舍（别装看不见）",
  "",
  "| 得到 | 付出 |",
  "| --- | --- |",
  "| 背负更轻 | 对失温/受伤/滞留的缓冲更小 |",
  "| 走得更轻松 | 「以防万一」的舒适物更少 |",
  "| 系统更简单 | 对技能与决策要求更高 |",
  "",
  "### 从哪里下手",
  "",
  "1. 先称你**已经在背**的所有东西（厨房秤 + 表格）。",
  "2. 优先动 **Big 3** 与 **打包衣物**。",
  "3. 导航、保暖、防雨、急救、修补、照明/点火等 **十项必备** 要按线路本地化，而不是照抄别人的克数。",
  "",
  "### 下方示例行",
  "",
  "可作为「起步行」合并进行程；**上路线前务必改成你自己的真实数据**。",
].join("\n");

const REI_FAK_EN = [
  "## Reading REI’s First Aid Kit Checklist",
  "",
  "REI’s article frames a **modular** kit: start from a compact commercial kit or DIY from categories, then add **trip-specific** layers (allergies, prescriptions, group size, remote duration, local hazards).",
  "",
  "### How to use this guide page",
  "",
  "- This page is **commentary** — the cloneable line-by-line checklist lives as a separate **blueprint** in this community library (`rei-first-aid-checklist`).",
  "- Weights in any checklist are **order-of-magnitude**; repack your own kit and re-weigh.",
  "",
  "### Mental model",
  "",
  "1. **Stop bleeding / protect airway** basics.",
  "2. **Blister / wound** care you will actually use.",
  "3. **Meds** you know how to administer (include instructions).",
  "4. **Evacuation signal** appropriate to terrain.",
  "",
  "### Training",
  "",
  "Carrying tools without training has limited value — consider a wilderness first aid course if you travel far from help.",
].join("\n");

const REI_FAK_ZH = [
  "## 如何阅读 REI《急救包清单》",
  "",
  "REI 原文把急救包当成 **模块化系统**：从市售小包或按类别 DIY 起步，再按 **行程** 叠加（过敏/处方药、队伍人数、远离救援的时长、当地风险）。",
  "",
  "### 本页定位",
  "",
  "- 这里是 **解读/导读**；可逐行克隆的装备清单在社区里另有一条蓝图：**`rei-first-aid-checklist`（急救包清单）**。",
  "- 任何清单上的重量都只是 **数量级**；请按你真实分装重新称重。",
  "",
  "### 心智模型",
  "",
  "1. **止血 / 气道保护** 的基础能力。",
  "2. 你真的会用的 **水泡与伤口** 处理材料。",
  "3. 你知道如何服用的 **药物**（附说明）。",
  "4. 与地形匹配的 **求救/撤离信号** 手段。",
  "",
  "### 培训",
  "",
  "只带工具不练技能收益有限 — 若常在远离救援处活动，建议考虑野外急救课程。",
].join("\n");

const big3ExampleItems: CommunityItem[] = [
  {
    name: "1P trekking-pole tarp (example)",
    nameZh: "单人天幕（示意）",
    weightG: 420,
    qty: 1,
    category: "misc",
    why: "Illustrative shelter line — swap for your real tent/tarp and measured weight.",
    whyZh: "庇护所示意行 — 请换成你的真实帐篷/天幕与称重。",
  },
  {
    name: "20°F quilt (example)",
    nameZh: "20°F 睡被（示意）",
    weightG: 680,
    qty: 1,
    category: "apparel",
    why: "Illustrative sleep insulation — rating must match your season and sleep style.",
    whyZh: "睡眠保暖示意 — 温标需匹配季节与个人体感。",
  },
  {
    name: "55L ultralight pack (example)",
    nameZh: "55L 超轻背包（示意）",
    weightG: 920,
    qty: 1,
    category: "misc",
    why: "Illustrative carry — volume and frame type dominate fit and comfort.",
    whyZh: "背负示意 — 容积与框架类型决定背负体感。",
  },
];

const ulExampleItems: CommunityItem[] = [
  {
    name: "DCF roll-top stuff sacks (set)",
    nameZh: "DCF 卷口防水袋（套装）",
    weightG: 38,
    qty: 2,
    category: "misc",
    why: "Keeps down dry; lighter than silnylon at small volumes.",
    whyZh: "保持羽绒干燥；小容积下比硅尼龙更轻。",
  },
  {
    name: "Titanium pot 900ml",
    nameZh: "钛锅 900ml",
    weightG: 125,
    qty: 1,
    category: "misc",
    why: "Cook + boil-in-bag with one vessel.",
    whyZh: "一锅兼顾煮水与袋餐。",
  },
  {
    name: "Long-handle titanium spoon",
    nameZh: "长柄钛勺",
    weightG: 15,
    qty: 1,
    category: "misc",
    why: "Avoids messy freezer-bag corners.",
    whyZh: "吃袋餐时不脏手。",
  },
  {
    name: "Mini BIC + firestarter backup",
    nameZh: "迷你 BIC + 备用打火",
    weightG: 24,
    qty: 1,
    category: "misc",
    why: "Redundant ignition under stress; practice before the trip.",
    whyZh: "压力下双重点火；行前练习。",
  },
  {
    name: "Polycryo ground sheet",
    nameZh: "Polycryo 地布",
    weightG: 40,
    qty: 1,
    category: "misc",
    why: "Protects air pad from punctures on gritty pads.",
    whyZh: "碎石营地保护气垫。",
  },
];

export const communityGuideSeeds: CommunityTemplate[] = [
  {
    type: "guide",
    id: "guide-big-three-explained",
    author: "PACKLOG",
    authorZh: "PACKLOG",
    rating: 4.75,
    cloned: 428,
    title: "What is the “Big 3”?",
    titleZh: "什么是「Big 3 / 三大件」？",
    scenario: "hiking",
    climate: "Concept · any trip",
    climateZh: "概念 · 任意行程",
    totalWeight: "≈2.0kg",
    totalWeightZh: "约 2.0kg",
    tags: ["big3", "concepts", "ultralight", "guide", "learning"],
    intro:
      "A short, non-dogmatic explainer of shelter / sleep / pack — plus three illustrative rows you can clone and edit.",
    introZh: "非教条式解释庇护所、睡眠与背负，并附三行可克隆后自行改写的示意装备。",
    markdown: BIG3_EN,
    markdownZh: BIG3_ZH,
    sourceUrl: "https://www.rei.com/learn/expert-advice/ultralight-backpacking-checklist.html",
    sourceTitle: "REI · Ultralight Backpacking Gear Checklist (context)",
    sourceTitleZh: "REI · 超轻徒步装备清单（背景阅读）",
    items: big3ExampleItems,
  },
  {
    type: "guide",
    id: "guide-ultralight-intro",
    author: "PACKLOG",
    authorZh: "PACKLOG",
    rating: 4.68,
    cloned: 612,
    title: "Ultralight backpacking — intro",
    titleZh: "超轻徒步入门（务实版）",
    scenario: "alpine",
    climate: "3-season · skills-dependent",
    climateZh: "三季 · 高度依赖技能与判断",
    totalWeight: "≈0.24kg",
    totalWeightZh: "约 0.24kg",
    tags: ["ultralight", "philosophy", "tradeoffs", "guide", "learning"],
    intro:
      "Trade-offs, rough base-weight context, and where to start — plus a few starter gear lines to merge into a trip.",
    introZh: "讲清楚取舍与粗略基础重量语境，并附几行可合并进行程的起步装备示例。",
    markdown: UL_EN,
    markdownZh: UL_ZH,
    sourceUrl: "https://www.rei.com/learn/expert-advice/ultralight-backpacking-checklist.html",
    sourceTitle: "REI · Ultralight Backpacking Gear Checklist",
    sourceTitleZh: "REI · 超轻徒步装备清单",
    items: ulExampleItems,
  },
  {
    type: "guide",
    id: "guide-rei-first-aid-read",
    author: "PACKLOG",
    authorZh: "PACKLOG",
    rating: 4.7,
    cloned: 305,
    title: "How to read REI’s first-aid checklist",
    titleZh: "如何阅读 REI《急救包清单》",
    scenario: "general",
    climate: "Any · preparedness",
    climateZh: "任意 · 行前准备",
    totalWeight: "—",
    totalWeightZh: "—",
    tags: ["first-aid", "rei", "wilderness", "guide", "learning"],
    intro:
      "Companion notes for REI’s article — the cloneable checklist is the separate blueprint `rei-first-aid-checklist` in this library.",
    introZh:
      "配合 REI 原文的导读 — 可逐行克隆的装备清单请在本社区打开蓝图 **rei-first-aid-checklist（急救包清单）**。",
    markdown: REI_FAK_EN,
    markdownZh: REI_FAK_ZH,
    sourceUrl: "https://www.rei.com/learn/expert-advice/first-aid-checklist.html",
    sourceTitle: "REI · First Aid Kit Checklist",
    sourceTitleZh: "REI · 急救包清单",
    items: [],
  },
];
