import type { CommunityTemplate } from "./packlog-data";

/**
 * Curated from REI Expert Advice — Ultralight Backpacking Gear Checklist
 * (Sarah Grothjan; article updated Mar 2026). Each `why` / `whyZh` summarizes
 * the article’s rationale; clone copies `why` into trip item notes.
 *
 * @see https://www.rei.com/learn/expert-advice/ultralight-backpacking-checklist.html
 */
export const reiUltralightCommunityTemplate: CommunityTemplate = {
  id: "rei-ultralight-backpacking-checklist",
  author: "REI Expert Advice",
  authorZh: "REI 专家推荐",
  rating: 4.95,
  cloned: 2406,
  title: "Ultralight Backpacking Gear Checklist",
  titleZh: "超轻徒步装备清单（REI）",
  scenario: "alpine",
  climate: "3-season mountains · variable",
  climateZh: "三季山地 · 天气变化大",
  totalWeight: "~15.3kg if every line checked",
  totalWeightZh: "全部勾选约 15.3kg",
  tags: ["ultralight", "backpacking", "rei", "3-season", "mountain"],
  sourceUrl: "https://www.rei.com/learn/expert-advice/ultralight-backpacking-checklist.html",
  sourceTitle: "Ultralight Backpacking Gear Checklist · REI",
  sourceTitleZh: "REI 超轻徒步装备清单",
  intro:
    "Curated from REI’s ultralight backpacking checklist (Sarah Grothjan, updated Mar 2026). Treat it as a gear menu—uncheck what your route does not need. Ten Essentials and local regulations still apply.",
  introZh:
    "整理自 REI《Ultralight Backpacking Gear Checklist》（Sarah Grothjan，2026 年 3 月更新）。这是装备菜单——按线路取消勾选即可；十项必备与当地法规仍然适用。",
  items: [
    {
      name: "Ultralight backpack (55–65L class)",
      nameZh: "超轻背包（约 55–65L 级别）",
      weightG: 920,
      qty: 1,
      category: "misc",
      why: "Pack, sleep system, and shelter are the bulkiest kit—trimming ounces here pays off fastest.",
      whyZh: "背包、睡眠与庇护所是体积重量大户，先从这里抠克数收益最大。",
    },
    {
      name: "Ultralight backpacking tent",
      nameZh: "超轻双人帐",
      weightG: 1180,
      qty: 1,
      category: "misc",
      why: "On dry nights you can leave the rainfly behind, or carry only rainfly + footprint (no body) to save weight.",
      whyZh: "干燥夜晚可省雨飞；或只带雨飞+地布、不要内帐，以换更轻。",
    },
    {
      name: "Flat tarp shelter",
      nameZh: "天幕 / 平幅 tarp",
      weightG: 380,
      qty: 1,
      category: "misc",
      why: "Minimalist shelter with no floor—coverage without full tent structure.",
      whyZh: "无地布的超简庇护所，用覆盖换结构重量。",
    },
    {
      name: "Bivy sack",
      nameZh: "露营袋（bivy）",
      weightG: 410,
      qty: 1,
      category: "misc",
      why: "Lightweight breathable barrier that protects your sleeping bag in mild bugs/wind.",
      whyZh: "轻量透气外壳，在虫少风弱时护住睡袋。",
    },
    {
      name: "Bug shelter (net + poles)",
      nameZh: "蚊帐庇护所（网纱+杆）",
      weightG: 360,
      qty: 1,
      category: "misc",
      why: "Netting and poles but no floor—keeps biting insects out.",
      whyZh: "网纱加杆、无地布，主打防叮咬昆虫。",
    },
    {
      name: "Ultralight hammock + suspension",
      nameZh: "超轻吊床 + 悬挂系统",
      weightG: 420,
      qty: 1,
      category: "misc",
      why: "Pair with a bug net or rainfly when you need modular protection.",
      whyZh: "可与防虫网或雨飞组合，模块化加减防护。",
    },
    {
      name: "Down sleeping bag (3-season)",
      nameZh: "羽绒睡袋（三季）",
      weightG: 820,
      qty: 1,
      category: "misc",
      why: "Down is lighter and more compressible than synthetic for the same warmth.",
      whyZh: "同保暖度下羽绒更轻、更易压缩。",
    },
    {
      name: "Backpacking quilt",
      nameZh: "睡袋被（quilt）",
      weightG: 480,
      qty: 1,
      category: "misc",
      why: "Top-only insulation—lighter than a full bag when your pad handles warmth.",
      whyZh: "只盖上面，睡垫承担部分保暖时可比信封睡袋更轻。",
    },
    {
      name: "Closed-cell foam sleeping pad",
      nameZh: "泡沫防潮垫（闭孔）",
      weightG: 420,
      qty: 1,
      category: "misc",
      why: "Typically the lightest pad style; durable on sharp ground.",
      whyZh: "通常是最轻的睡垫方案，耐碎石地。",
    },
    {
      name: "Inflatable air sleeping pad",
      nameZh: "充气睡垫",
      weightG: 520,
      qty: 1,
      category: "misc",
      why: "Often warmer loft than foam when R-value matters—watch punctures.",
      whyZh: "R 值需求高时通常比泡沫更暖，但要防扎破。",
    },
    {
      name: "Pack liner (dry sack)",
      nameZh: "背包内防水袋 / 内衬",
      weightG: 45,
      qty: 1,
      category: "misc",
      why: "Space-saving alternative to a pack cover—keeps gear dry in showers.",
      whyZh: "比外罩更省空间，阵雨里保持包内干燥。",
    },
    {
      name: "Ultralight trekking poles (fixed-length)",
      nameZh: "超轻登山杖（固定长度）",
      weightG: 440,
      qty: 1,
      category: "misc",
      why: "Fixed poles drop adjusters; REI classifies ultralight poles under ~1 lb per pair.",
      whyZh: "无调节节段更轻；REI 将「每对约 1 磅以下」视作超轻杖。",
    },
    {
      name: "Tent footprint",
      nameZh: "帐篷地布",
      weightG: 170,
      qty: 1,
      category: "misc",
      why: "Adds weight but protects floor life on abrasive ground.",
      whyZh: "增重，但能保护帐底寿命。",
    },
    {
      name: "Inflatable camp pillow",
      nameZh: "充气枕头",
      weightG: 75,
      qty: 1,
      category: "misc",
      why: "A couple of ounces can buy noticeably better sleep.",
      whyZh: "多花几克换睡眠质量，很多人愿意。",
    },
    {
      name: "Bear spray (if required)",
      nameZh: "防熊喷雾（如需）",
      weightG: 290,
      qty: 1,
      category: "misc",
      why: "Some national parks require it—always check local regulations.",
      whyZh: "部分国家公园强制或建议携带，务必查当地规定。",
    },
    {
      name: "Backpacking stove (tablet / alcohol class)",
      nameZh: "炉头（固体酒精 / 酒精类）",
      weightG: 75,
      qty: 1,
      category: "misc",
      why: "Tablet and alcohol stoves are often the lightest cooking options.",
      whyZh: "固体燃料与酒精炉常是最轻的烹饪方案之一。",
    },
    {
      name: "Stove fuel (matched to stove)",
      nameZh: "燃料（与炉头匹配）",
      weightG: 95,
      qty: 1,
      category: "misc",
      why: "Confirm compatibility between stove head and fuel before you pack.",
      whyZh: "出发前确认炉头与燃料种类匹配。",
    },
    {
      name: "Mini lighter + backup ignition",
      nameZh: "迷你打火机 + 备用点火",
      weightG: 18,
      qty: 1,
      category: "misc",
      why: "Tiny but critical for windy or damp evenings.",
      whyZh: "体积小但在潮湿有风夜晚很关键。",
    },
    {
      name: "Titanium mug / pot combo",
      nameZh: "钛杯 / 套锅一体",
      weightG: 165,
      qty: 1,
      category: "misc",
      why: "One pot that doubles as a mug saves duplicate metal.",
      whyZh: "一锅兼杯，少带一件金属器皿。",
    },
    {
      name: "Ultralight spork",
      nameZh: "超轻勺叉一体",
      weightG: 12,
      qty: 1,
      category: "misc",
      why: "A simple spork is usually all you need in the backcountry.",
      whyZh: "野餐一把 spork 往往够用。",
    },
    {
      name: "Cut sponge / dish scrubber",
      nameZh: "切半洗碗海绵",
      weightG: 8,
      qty: 1,
      category: "misc",
      why: "Buy full sponge and cut in half—share the other half with a trail friend.",
      whyZh: "整片海绵切半，另一半可分给同伴，省空间。",
    },
    {
      name: "Odor-proof food bag",
      nameZh: "防味食物袋",
      weightG: 85,
      qty: 1,
      category: "misc",
      why: "Helps keep bears and critters from investigating your calories.",
      whyZh: "降低熊与其他动物被食物气味吸引的概率。",
    },
    {
      name: "Bear-resistant canister (if required)",
      nameZh: "防熊罐（如强制要求）",
      weightG: 820,
      qty: 1,
      category: "misc",
      why: "Soft bags don’t always cut it—some parks require hard-sided storage; modular cans can double as pack structure.",
      whyZh: "软袋不一定合规；部分园区要求硬壳储食，模块化罐体还能当打包支撑。",
    },
    {
      name: "Trash bag + mesh grey-water strainer",
      nameZh: "垃圾袋 + 滤食物残渣网",
      weightG: 35,
      qty: 1,
      category: "misc",
      why: "Pack all waste out; strain food particles from dish water per site rules.",
      whyZh: "垃圾全带出；洗碗水按当地要求过滤食物颗粒。",
    },
    {
      name: "Squeeze / straw water filter",
      nameZh: "挤压 / 吸管式净水器",
      weightG: 68,
      qty: 1,
      category: "misc",
      why: "Among the lightest treatment styles for gram counters.",
      whyZh: "对抠克数的人，这是最轻的一类净水方案之一。",
    },
    {
      name: "Chemical purification tablets (backup)",
      nameZh: "净水片（备份）",
      weightG: 25,
      qty: 1,
      category: "misc",
      why: "Alternative to filters; repackage into a baggie to save bottle weight unless directions forbid it.",
      whyZh: "可作滤芯备份；说明书允许时可拆原瓶改小袋减重。",
    },
    {
      name: "Collapsible soft water bottles",
      nameZh: "可折叠软水壶",
      weightG: 42,
      qty: 2,
      category: "misc",
      why: "Roll down as you drink to reclaim pack volume.",
      whyZh: "喝掉后卷起来，省包内空间。",
    },
    {
      name: "Trail-running or light hiking shoes",
      nameZh: "越野跑鞋或轻量徒步鞋",
      weightG: 540,
      qty: 1,
      category: "apparel",
      why: "Trail runners are usually lightest; boots trade grams for ankle support.",
      whyZh: "越野跑鞋通常最轻；高帮靴用重量换脚踝支撑。",
    },
    {
      name: "Merino wool T-shirt",
      nameZh: "美利奴羊毛 T 恤",
      weightG: 155,
      qty: 1,
      category: "apparel",
      why: "Wool resists odor bacteria—solid for multi-day smell control.",
      whyZh: "羊毛抑菌抑味，多日连穿更友好。",
    },
    {
      name: "Breathable hiking shorts",
      nameZh: "透气徒步短裤",
      weightG: 170,
      qty: 1,
      category: "apparel",
      why: "Thru-hiking? Pick a drawstring so fit still works as your body changes.",
      whyZh: "长线可选抽绳腰围，体型变化时仍能调节。",
    },
    {
      name: "Convertible hiking pants",
      nameZh: "两截速干徒步裤",
      weightG: 320,
      qty: 1,
      category: "apparel",
      why: "Zip-offs cover stream crossings, cool mornings, and hot afternoons.",
      whyZh: "拉链裤腿应对过河、清晨凉、午后热。",
    },
    {
      name: "Quick-dry underwear",
      nameZh: "速干内裤",
      weightG: 35,
      qty: 2,
      category: "apparel",
      why: "Avoid cotton—wool or polyester wicks moisture.",
      whyZh: "避免纯棉，羊毛或涤纶更排汗。",
    },
    {
      name: "Padded hiking socks",
      nameZh: "缓冲徒步袜",
      weightG: 48,
      qty: 2,
      category: "apparel",
      why: "Padding makes multi-day miles easier on your feet.",
      whyZh: "缓冲让多日里程对脚更友好。",
    },
    {
      name: "UPF sun hat",
      nameZh: "防晒遮阳帽",
      weightG: 58,
      qty: 1,
      category: "apparel",
      why: "Wide brim + UPF fabric protects without constant sunscreen reapplication.",
      whyZh: "宽檐 + UPF 面料，减少反复补涂防晒霜。",
    },
    {
      name: "Sun sleeves (optional)",
      nameZh: "防晒袖套（可选）",
      weightG: 34,
      qty: 1,
      category: "apparel",
      why: "Easy on/off sun armor while you move.",
      whyZh: "行进间可快速穿脱的防晒层。",
    },
    {
      name: "Multifunction bandana",
      nameZh: "多功能头巾",
      weightG: 24,
      qty: 1,
      category: "apparel",
      why: "Neck shade, pack flair, or dip in a creek for evaporative cooling.",
      whyZh: "护颈、装饰包袋，或浸水降温。",
    },
    {
      name: "Merino long-underwear top (sleep)",
      nameZh: "美利奴长袖打底（睡觉）",
      weightG: 175,
      qty: 1,
      category: "apparel",
      why: "Dedicated sleep layer smells better next morning than trail grime.",
      whyZh: "睡觉专用层，第二天气味比穿脏 trail 衣好得多。",
    },
    {
      name: "Merino long-underwear bottoms (sleep)",
      nameZh: "美利奴长裤打底（睡觉）",
      weightG: 160,
      qty: 1,
      category: "apparel",
      why: "Wool resists odor—nice for multi-night camp hygiene.",
      whyZh: "羊毛抑味，多日营地卫生更省心。",
    },
    {
      name: "Warm beanie",
      nameZh: "保暖毛线帽",
      weightG: 48,
      qty: 1,
      category: "apparel",
      why: "Temps often drop fast after sunset—even in summer mountains.",
      whyZh: "日落降温快，夏季山里也可能需要。",
    },
    {
      name: "Sleep-only wool socks",
      nameZh: "仅睡觉穿的羊毛袜",
      weightG: 60,
      qty: 1,
      category: "apparel",
      why: "Never sleep in sweaty socks—damp feet feel colder.",
      whyZh: "别穿汗湿袜入睡，潮湿脚更怕冷。",
    },
    {
      name: "Down puffy jacket or vest",
      nameZh: "羽绒外套或羽绒马甲",
      weightG: 360,
      qty: 1,
      category: "apparel",
      why: "Down is lighter and more compressible than synthetic puffies.",
      whyZh: "羽绒通常比化纤棉服更轻更易压缩。",
    },
    {
      name: "Light camp sandals",
      nameZh: "轻便营地凉鞋",
      weightG: 210,
      qty: 1,
      category: "misc",
      why: "Helpful for river crossings and lounging around camp.",
      whyZh: "过河与营地放松都好用。",
    },
    {
      name: "Rain jacket with pit zips",
      nameZh: "带腋下拉链的雨衣",
      weightG: 335,
      qty: 1,
      category: "apparel",
      why: "Pit zips ventilate while you move so you don’t boil inside the shell.",
      whyZh: "腋下拉链便于行进透气，减少「蒸桑拿」。",
    },
    {
      name: "Rain pants with ankle zips",
      nameZh: "带脚踝拉链的雨裤",
      weightG: 275,
      qty: 1,
      category: "apparel",
      why: "Ankle zips let you pull them on/off without removing shoes in surprise storms.",
      whyZh: "侧拉链便于突变天气时穿鞋穿脱雨裤。",
    },
    {
      name: "Waterproof warm gloves",
      nameZh: "防水保暖手套",
      weightG: 115,
      qty: 1,
      category: "apparel",
      why: "Waterproof versions keep fingers dry for camp chores.",
      whyZh: "防水款让手指干爽，营地操作更利索。",
    },
    {
      name: "Waterproof topo map",
      nameZh: "防水地形图",
      weightG: 55,
      qty: 1,
      category: "doc",
      why: "Carry the trails you intend to hike—print on waterproof paper if you can.",
      whyZh: "携带计划路线；可打印在防水纸上。",
    },
    {
      name: "Baseplate compass",
      nameZh: "底板指南针",
      weightG: 38,
      qty: 1,
      category: "doc",
      why: "Brush up on map + compass basics before relying on electronics alone.",
      whyZh: "在只信电子导航前，先复习地图与罗盘基础。",
    },
    {
      name: "Portable battery pack",
      nameZh: "移动电源",
      weightG: 240,
      qty: 1,
      category: "tech",
      why: "Recharge phone, GPS, or satellite messenger in the field.",
      whyZh: "野外给手机、GPS、卫星通讯器补电。",
    },
    {
      name: "Handheld GPS with maps",
      nameZh: "手持 GPS（含地图）",
      weightG: 215,
      qty: 1,
      category: "tech",
      why: "Preloaded maps, electronic compass, and altimeter help on long trails.",
      whyZh: "预装地图、电子罗盘、高度计，长线更安心。",
    },
    {
      name: "Satellite communicator or PLB",
      nameZh: "卫星通讯器或个人信标（PLB）",
      weightG: 180,
      qty: 1,
      category: "tech",
      why: "Messenger gives two-way texting; PLB sends one-way SOS—pick for your risk profile.",
      whyZh: "卫星信使可双向短信；PLB 多为单向求救——按风险选择。",
    },
    {
      name: "Route photocopies / guidebook pages",
      nameZh: "路线复印件 / 指南书摘页",
      weightG: 20,
      qty: 1,
      category: "doc",
      why: "Photocopy key pages instead of hauling the whole guidebook.",
      whyZh: "复印关键页，少背整本指南。",
    },
    {
      name: "Permits + ID bundle",
      nameZh: "许可证 + 证件套装",
      weightG: 40,
      qty: 1,
      category: "doc",
      why: "Many trailheads require parking, hiking, and/or camping permits—research early.",
      whyZh: "许多路线需停车/徒步/露营许可，提前查清。",
    },
    {
      name: "Sunscreen + SPF lip balm",
      nameZh: "防晒霜 + 带防晒润唇膏",
      weightG: 82,
      qty: 1,
      category: "health",
      why: "Stick sunscreen is light and long-lasting; lips burn fast at altitude.",
      whyZh: "棒状防晒轻便耐补；高海拔嘴唇也易晒伤。",
    },
    {
      name: "Insect repellent (small)",
      nameZh: "小瓶装驱虫剂",
      weightG: 42,
      qty: 1,
      category: "health",
      why: "Small bottles or single-use packets save bulk.",
      whyZh: "小瓶或单片装省体积。",
    },
    {
      name: "Keychain hand sanitizer",
      nameZh: "挂扣式免洗洗手液",
      weightG: 32,
      qty: 1,
      category: "health",
      why: "Clip to pack for privy visits and meal prep hygiene.",
      whyZh: "挂包上，方便如厕与餐前清洁。",
    },
    {
      name: "Toothpaste tablets + mini toothbrush",
      nameZh: "牙膏粒 + 迷你牙刷",
      weightG: 22,
      qty: 1,
      category: "health",
      why: "Travel sizes save weight; some ultralighters shorten handles or pack brush heads only.",
      whyZh: "旅行装减重；有人锯短柄或只带头。",
    },
    {
      name: "Biodegradable camp soap (tiny)",
      nameZh: "可降解营地皂（极小装）",
      weightG: 48,
      qty: 1,
      category: "health",
      why: "Wash dishes, hands, face, and hair—use sparingly and away from water sources.",
      whyZh: "洗碗洗手洗脸洗发都要远离水源、少量使用。",
    },
    {
      name: "Pre-moistened wipes (pack-out)",
      nameZh: "湿巾（必须带出）",
      weightG: 110,
      qty: 1,
      category: "health",
      why: "If you use wipes you must pack them out—no burying.",
      whyZh: "用湿巾就必须全数带出，不能掩埋。",
    },
    {
      name: "Mini toilet paper roll",
      nameZh: "迷你卫生纸卷",
      weightG: 35,
      qty: 1,
      category: "health",
      why: "Flatten squares into a zip bag vs hauling a bulky roll.",
      whyZh: "把纸压平装袋，比整卷省空间。",
    },
    {
      name: "Antimicrobial pee cloth",
      nameZh: "抗菌小便巾（可水洗复用）",
      weightG: 34,
      qty: 1,
      category: "health",
      why: "Reusable on multi-day trips with proper rinse routine.",
      whyZh: "多日行程可冲洗复用，减少一次性垃圾。",
    },
    {
      name: "Ultralight trowel",
      nameZh: "超轻户外铲",
      weightG: 52,
      qty: 1,
      category: "misc",
      why: "Some areas require catholes—follow local guidance on human waste.",
      whyZh: "部分地区要求挖坑掩埋排泄物，务必遵守当地规范。",
    },
    {
      name: "Custom ultralight first-aid kit",
      nameZh: "自配超轻急救包",
      weightG: 175,
      qty: 1,
      category: "health",
      why: "Control weight/size by tailoring to trip length, group, and remoteness.",
      whyZh: "按天数、人数、偏远度自配，控制体积重量。",
    },
    {
      name: "Safety whistle + lanyard",
      nameZh: "求生哨 + 挂绳",
      weightG: 8,
      qty: 1,
      category: "misc",
      why: "Louder than shouting—wildlife deterrence and SAR signaling.",
      whyZh: "比喊叫传得更远，可驱离动物或求救。",
    },
    {
      name: "Emergency bivy / space blanket",
      nameZh: "应急露营袋 / 急救毯",
      weightG: 95,
      qty: 1,
      category: "health",
      why: "Under ~3 oz insurance against an unplanned night out.",
      whyZh: "不足百克，为意外过夜买份保险。",
    },
    {
      name: "Stormproof matches + fire starters",
      nameZh: "防水火柴 + 引火块",
      weightG: 36,
      qty: 1,
      category: "misc",
      why: "Carry reliable ignition for rainy or windy evenings.",
      whyZh: "风雨夜需要可靠点火手段。",
    },
    {
      name: "Itinerary copies for trusted contact",
      nameZh: "行程复印件（交给亲友）",
      weightG: 15,
      qty: 1,
      category: "doc",
      why: "Share plans with someone who knows where you are and when you return.",
      whyZh: "把行程交给知道你何时归来的人。",
    },
    {
      name: "Small knife / multi-tool",
      nameZh: "小刀 / 多功能工具",
      weightG: 48,
      qty: 1,
      category: "misc",
      why: "Repairs, food prep, and first-aid chores.",
      whyZh: "修装备、备餐、急救杂务都能用上。",
    },
    {
      name: "Ultralight headlamp + spare batteries",
      nameZh: "超轻头灯 + 备用电池",
      weightG: 85,
      qty: 1,
      category: "tech",
      why: "Many ultralight headlamps weigh under two ounces with enough camp lumens.",
      whyZh: "很多 UL 头灯不到两盎司仍能照亮营地。",
    },
    {
      name: "Polarized sunglasses",
      nameZh: "偏光太阳镜",
      weightG: 38,
      qty: 1,
      category: "optic",
      why: "Polarized lenses help in high-glare snow or water travel.",
      whyZh: "雪地或水面高眩光环境更舒服。",
    },
    {
      name: "Mosquito head net",
      nameZh: "防蚊头网",
      weightG: 34,
      qty: 1,
      category: "misc",
      why: "Tiny insurance on buggy approaches.",
      whyZh: "蚊虫多的接近路段，轻量保险。",
    },
    {
      name: "Leg gaiters",
      nameZh: "雪套 / 护腿",
      weightG: 155,
      qty: 1,
      category: "apparel",
      why: "Snow or sand—keep debris out of boots.",
      whyZh: "雪线或沙地，防止碎屑进鞋。",
    },
    {
      name: "Micro traction / Kahtoola-style spikes",
      nameZh: "简易冰爪 / 鞋钉",
      weightG: 160,
      qty: 1,
      category: "misc",
      why: "Extra grip on icy shoulder-season crossings.",
      whyZh: "肩季结冰路面增加抓地。",
    },
    {
      name: "Seasonal ice axe",
      nameZh: "季节款冰镐",
      weightG: 480,
      qty: 1,
      category: "misc",
      why: "Thru-hikers often carry when lingering snow still plugs passes.",
      whyZh: "融雪期山口仍有积雪时，长线徒步者常会携带。",
    },
    {
      name: "Ultralight gear repair kit",
      nameZh: "超轻装备维修包",
      weightG: 75,
      qty: 1,
      category: "misc",
      why: "Zipper jams, pad punctures, or torn shelters get uncomfortable fast—carry the right bits.",
      whyZh: "拉链、睡垫、帐篷出问题会迅速变糟，带齐小修件。",
    },
    {
      name: "Cash + emergency credit card",
      nameZh: "现金 + 应急信用卡",
      weightG: 13,
      qty: 1,
      category: "doc",
      why: "Trail towns and hitches still run on cash; stash card deep in the pack.",
      whyZh: "小镇补给与搭车仍常用现金；卡放在不常开的夹层防丢。",
    },
    {
      name: "Cell phone (offline maps)",
      nameZh: "手机（离线地图）",
      weightG: 220,
      qty: 1,
      category: "tech",
      why: "Airplane mode or powered off stretches battery for camera + emergency comms.",
      whyZh: "飞行模式或关机可省电量，兼顾相机与应急联络。",
    },
    {
      name: "Compact camera or action cam (luxury)",
      nameZh: "小型相机 / 运动相机（享受级）",
      weightG: 310,
      qty: 1,
      category: "optic",
      why: "Going light on essentials can leave room for sunrise memories beyond a phone.",
      whyZh: "必需品抠下来的空间，可留给日出回忆。",
    },
    {
      name: "Compact binoculars (luxury)",
      nameZh: "小型双筒望远镜（享受级）",
      weightG: 360,
      qty: 1,
      category: "optic",
      why: "Neck strap keeps optics within reach on wildlife stops.",
      whyZh: "挂颈便于观鸟观兽时随手取用。",
    },
    {
      name: "Weatherproof journal + pen (luxury)",
      nameZh: "防水笔记本 + 笔（享受级）",
      weightG: 113,
      qty: 1,
      category: "doc",
      why: "Weatherproof pages survive sweat and drizzle for sketches or trail notes.",
      whyZh: "防水页扛汗雾 drizzle，适合速写或记录。",
    },
  ],
};
