import type { CommunityTemplate } from "./packlog-data";

/**
 * Curated from REI Expert Advice — First Aid Kit Checklist.
 * Opening guidance: carry a prepackaged kit or DIY from this list; knowing how
 * to use items matters as much as carrying them (consider formal training).
 * Add group prescriptions and trip-specific extras for destination and duration.
 *
 * @see https://www.rei.com/learn/expert-advice/first-aid-checklist.html
 */
export const reiFirstAidCommunityTemplate: CommunityTemplate = {
  id: "rei-first-aid-checklist",
  author: "REI Expert Advice",
  rating: 4.92,
  cloned: 3120,
  title: "First Aid Kit Checklist",
  titleZh: "急救包清单（REI）",
  scenario: "alpine",
  climate: "Outdoor · any season",
  totalWeight: "~1.7kg if every line checked",
  tags: ["first-aid", "rei", "wilderness", "health", "emergency"],
  sourceUrl: "https://www.rei.com/learn/expert-advice/first-aid-checklist.html",
  sourceTitle: "First Aid Kit Checklist · REI",
  intro:
    "From REI’s first-aid kit checklist: carry a store-bought kit or build your own using these rows. Using the kit correctly matters as much as packing it—REI suggests taking a training course. This is a starting point; add prescription meds for your group and extra supplies for where you’re going and how long you’ll be out. Some “emergency essentials” may live outside the kit in your pack.",
  introZh:
    "整理自 REI《First Aid Kit Checklist》。要点：要么带成品急救包，要么按下列目自制；会用和带齐同样重要，文章建议参加急救培训。清单是起点，请补充全队处方药，并按目的地与外出时长加减物资。部分「应急必备」可单独放在包内、不必全塞进小药包。",
  items: [
    {
      name: "Antiseptic wipes (BZK preferred; alcohol OK)",
      nameZh: "消毒湿巾（优先苯扎氯铵 BZK；含酒精亦可）",
      weightG: 28,
      qty: 1,
      category: "health",
      why: "REI prefers BZK-based wipes; alcohol-based is acceptable per the checklist.",
      whyZh: "原文写 BZK 类更推荐，含酒精款也可接受。",
    },
    {
      name: "Antibacterial ointment (e.g., bacitracin)",
      nameZh: "抗菌软膏（如杆菌肽）",
      weightG: 14,
      qty: 1,
      category: "health",
      why: "Listed for basic wound care after cleaning.",
      whyZh: "基础护理：清创后涂敷防感染。",
    },
    {
      name: "Compound tincture of benzoin",
      nameZh: "复方安息香酊（敷料粘合助剂）",
      weightG: 12,
      qty: 1,
      category: "health",
      why: "REI lists it specifically to improve bandage/tape adhesion on skin.",
      whyZh: "原文用于增强绷带/胶布在皮肤上的附着。",
    },
    {
      name: "Assorted adhesive bandages (fabric preferred)",
      nameZh: "各式创可贴（布料型更推荐）",
      weightG: 35,
      qty: 1,
      category: "health",
      why: "Fabric bandages are preferred in the article for durability and comfort.",
      whyZh: "原文更推荐布料型，耐用与贴合度通常更好。",
    },
    {
      name: "Butterfly bandages / adhesive wound-closure strips",
      nameZh: "蝶形胶布 / 免缝伤口闭合贴",
      weightG: 8,
      qty: 1,
      category: "health",
      why: "For approximating wound edges when you need more than a flat bandage.",
      whyZh: "比平贴更能拉拢切口边缘，小伤口临时闭合。",
    },
    {
      name: "Gauze pads (assorted sizes)",
      nameZh: "纱布垫（多种尺寸）",
      weightG: 40,
      qty: 1,
      category: "health",
      why: "Basic absorbent layers for bleeding and dressing changes.",
      whyZh: "吸血与换药的基础垫层。",
    },
    {
      name: "Nonstick sterile pads",
      nameZh: "无菌不粘垫",
      weightG: 25,
      qty: 1,
      category: "health",
      why: "Reduces dressing sticking to a healing wound.",
      whyZh: "减少敷料与创面粘连。",
    },
    {
      name: 'Medical adhesive tape (≥1" wide, ≥10 yd roll)',
      nameZh: "医用胶布（宽≥1 英寸，卷≥10 码）",
      weightG: 45,
      qty: 1,
      category: "health",
      why: "Checklist specifies minimum width and length for securing dressings.",
      whyZh: "原文规定最小宽度与长度，便于固定敷料。",
    },
    {
      name: "Blister treatment supplies",
      nameZh: "水泡处理用品",
      weightG: 22,
      qty: 1,
      category: "health",
      why: "Dedicated blister care is its own checklist line on REI’s list.",
      whyZh: "REI 单独列出，徒步常见伤，应备专用处理材料。",
    },
    {
      name: "Ibuprofen / pain-relief medication",
      nameZh: "布洛芬 / 止痛药",
      weightG: 12,
      qty: 1,
      category: "health",
      why: "Listed under basic care for pain and inflammation management.",
      whyZh: "基础药箱：止痛与抗炎。",
    },
    {
      name: "Insect sting / anti-itch treatment",
      nameZh: "虫咬止痒 / 螫伤处理剂",
      weightG: 18,
      qty: 1,
      category: "health",
      why: "Addresses stings and itchy bites common outdoors.",
      whyZh: "户外常见螫咬与瘙痒对症处理。",
    },
    {
      name: "Antihistamine (allergic reactions)",
      nameZh: "抗组胺药（过敏反应）",
      weightG: 10,
      qty: 1,
      category: "health",
      why: "REI calls out antihistamines specifically for allergic reactions.",
      whyZh: "原文写明用于过敏反应。",
    },
    {
      name: "Fine-point splinter tweezers",
      nameZh: "尖头镊子（取刺）",
      weightG: 12,
      qty: 1,
      category: "misc",
      why: "Fine-point style is what the checklist specifies for splinters.",
      whyZh: "原文强调尖头，便于取木刺等异物。",
    },
    {
      name: "Safety pins",
      nameZh: "安全别针",
      weightG: 5,
      qty: 4,
      category: "misc",
      why: "Small multipurpose fasteners for slings, gear, or improvised fixes.",
      whyZh: "小体积多用途：悬带、装备或临时固定。",
    },
    {
      name: "First-aid manual or information cards",
      nameZh: "急救手册或信息卡",
      weightG: 55,
      qty: 1,
      category: "doc",
      why: "REI pairs supplies with reference material you can follow under stress.",
      whyZh: "有物资还要能在紧张时按步骤操作，原文列入手册/卡片。",
    },
    {
      name: "Elastic wrap (e.g., ACE-style)",
      nameZh: "弹性绷带（自粘/弹力）",
      weightG: 38,
      qty: 1,
      category: "health",
      why: "Compression and support for sprains/strains per wraps section.",
      whyZh: "扭伤拉伤加压包扎与支撑。",
    },
    {
      name: "Triangular cravat bandage",
      nameZh: "三角巾 / 宽绷带",
      weightG: 42,
      qty: 1,
      category: "health",
      why: "Classic multipurpose sling, swathe, or broad bandage.",
      whyZh: "经典多用：悬臂、固定或宽包扎。",
    },
    {
      name: "Finger splint(s)",
      nameZh: "手指夹板",
      weightG: 18,
      qty: 2,
      category: "health",
      why: "Immobilize finger injuries until definitive care.",
      whyZh: "固定指伤直至进一步处置。",
    },
    {
      name: "SAM splint(s) or moldable splint",
      nameZh: "SAM 夹板 / 可塑夹板",
      weightG: 120,
      qty: 1,
      category: "misc",
      why: "REI lists SAM-style splints for versatile limb immobilization.",
      whyZh: "原文列 SAM 类，四肢固定方案灵活。",
    },
    {
      name: "Rolled gauze",
      nameZh: "卷状纱布",
      weightG: 22,
      qty: 1,
      category: "health",
      why: "Conforms to limbs for bulk dressings and retention.",
      whyZh: "贴合肢体，做加压包扎或固定外层。",
    },
    {
      name: "Rolled stretch-to-conform bandages",
      nameZh: "自粘/可拉伸贴合绷带卷",
      weightG: 28,
      qty: 1,
      category: "health",
      why: "Listed separately from plain rolled gauze for conforming wraps.",
      whyZh: "与纱布卷并列，原文强调可拉伸贴合包扎。",
    },
    {
      name: "Hydrogel burn / wound pads",
      nameZh: "水凝胶敷料（烧伤/创面）",
      weightG: 30,
      qty: 2,
      category: "health",
      why: "Hydrogel pads are explicitly named in the wound-coverings section.",
      whyZh: "原文单独列水凝胶垫，利于部分烧伤或创面护理。",
    },
    {
      name: "First-aid cleansing pads with topical anesthetic",
      nameZh: "含表面麻醉的清洁棉片",
      weightG: 16,
      qty: 1,
      category: "health",
      why: "Clean while reducing pain from minor wound care.",
      whyZh: "清创同时减轻刺痛，便于处理小伤口。",
    },
    {
      name: "Hemostatic (blood-stopping) gauze",
      nameZh: "止血纱布（促凝）",
      weightG: 18,
      qty: 1,
      category: "health",
      why: "REI lists hemostatic gauze for serious bleeding scenarios.",
      whyZh: "原文列止血纱布，用于严重出血场景（需培训配合）。",
    },
    {
      name: "Liquid bandage",
      nameZh: "液体创可贴",
      weightG: 8,
      qty: 1,
      category: "health",
      why: "Film seal over small clean cuts when tape won’t stick well.",
      whyZh: "小切口成膜密封，胶布不易贴牢时的补充。",
    },
    {
      name: "Group prescription medications",
      nameZh: "全队处方药（按医嘱）",
      weightG: 80,
      qty: 1,
      category: "health",
      why: "Article: include any prescription meds your group needs—non-optional personalization.",
      whyZh: "原文强调必须带上全队所需处方药，无法由通用清单替代。",
    },
    {
      name: "Sunburn relief gel or spray",
      nameZh: "晒后舒缓凝胶或喷雾",
      weightG: 45,
      qty: 1,
      category: "health",
      why: "Listed under additional medications for UV overexposure symptoms.",
      whyZh: "晒伤对症，原文列在附加药品类。",
    },
    {
      name: "Throat lozenges",
      nameZh: "润喉糖",
      weightG: 25,
      qty: 1,
      category: "health",
      why: "Comfort for dry, irritated throat on long cold or windy days.",
      whyZh: "寒冷大风天咽部干痛舒缓。",
    },
    {
      name: "Lubricating eye drops",
      nameZh: "润滑滴眼液",
      weightG: 18,
      qty: 1,
      category: "health",
      why: "Dry eye relief from wind, dust, or altitude irritation.",
      whyZh: "风沙或高海拔眼干刺激缓解。",
    },
    {
      name: "Diarrhea medication",
      nameZh: "止泻药",
      weightG: 8,
      qty: 1,
      category: "health",
      why: "Listed for GI upset that can dehydrate quickly in the backcountry.",
      whyZh: "野外腹泻易脱水，原文列入对症药物。",
    },
    {
      name: "Antacid tablets",
      nameZh: "抗酸胃药（咀嚼片等）",
      weightG: 12,
      qty: 1,
      category: "health",
      why: "Addresses heartburn/indigestion that can ruin a long day.",
      whyZh: "烧心消化不良影响行程，作对症备用。",
    },
    {
      name: "Oral rehydration salts (ORS)",
      nameZh: "口服补液盐 ORS",
      weightG: 40,
      qty: 2,
      category: "health",
      why: "REI lists ORS to replace electrolytes during vomiting/diarrhea or heavy sweat.",
      whyZh: "呕吐腹泻或大出汗时补电解质，原文单独列出。",
    },
    {
      name: "Glucose / fast sugar (hypoglycemia)",
      nameZh: "葡萄糖或快糖（低血糖）",
      weightG: 30,
      qty: 1,
      category: "health",
      why: "Checklist names glucose or other sugar to treat hypoglycemia.",
      whyZh: "原文写明用于低血糖快速升糖。",
    },
    {
      name: "Injectable epinephrine (severe allergy)",
      nameZh: "肾上腺素自动注射器（严重过敏，遵医嘱）",
      weightG: 60,
      qty: 1,
      category: "health",
      why: "REI lists injectable epinephrine for severe allergic reactions—requires prescription and training.",
      whyZh: "原文列注射用肾上腺素应对严重过敏；需处方与使用培训。",
    },
    {
      name: "Aspirin (heart attack response)",
      nameZh: "阿司匹林（疑似心梗时按指南使用）",
      weightG: 6,
      qty: 1,
      category: "health",
      why: "Article notes aspirin primarily for suspected heart attack response per guidance you’ve learned.",
      whyZh: "原文写明主要用于疑似心梗场景，须在培训/指南指导下使用。",
    },
    {
      name: "Knife or multi-tool with knife blade",
      nameZh: "小刀或带刀片的组合工具",
      weightG: 85,
      qty: 1,
      category: "misc",
      why: "REI lists knife or multi-tool as core kit tools—not only for gear repair.",
      whyZh: "原文列在工具类，急救与装备维修都可能用到刀刃。",
    },
    {
      name: "Paramedic shears (blunt-tip trauma scissors)",
      nameZh: "急救剪（圆头创伤剪）",
      weightG: 48,
      qty: 1,
      category: "misc",
      why: "Blunt tips reduce risk when cutting clothing or bandages near skin.",
      whyZh: "圆头降低剪衣/剪绷带时刺伤皮肤的风险。",
    },
    {
      name: "Safety razor blade or scalpel (#15 or #12)",
      nameZh: "安全剃刀片或手术刀（#15 / #12）",
      weightG: 4,
      qty: 1,
      category: "misc",
      why: "Checklist offers razor blade or scalpel with specific blade numbers—pack and store safely.",
      whyZh: "原文给出刀片型号选项，务必安全收纳与谨慎使用。",
    },
    {
      name: "Cotton-tipped swabs",
      nameZh: "棉签",
      weightG: 8,
      qty: 6,
      category: "health",
      why: "Small applicators for ointments and precise cleaning.",
      whyZh: "上药与精细清创的小工具。",
    },
    {
      name: "Standard oral thermometer",
      nameZh: "口腔体温计（标准款）",
      weightG: 12,
      qty: 1,
      category: "health",
      why: "Objective fever data helps decide evacuation urgency.",
      whyZh: "客观体温帮助判断是否需下撤求医。",
    },
    {
      name: "Irrigation syringe with 18-gauge catheter",
      nameZh: "冲洗注射器 + 18G 导管",
      weightG: 25,
      qty: 1,
      category: "health",
      why: "REI specifies syringe plus 18-gauge catheter for wound irrigation technique.",
      whyZh: "原文指定规格，用于规范伤口冲洗（需培训）。",
    },
    {
      name: "Medical gloves (nitrile preferred; avoid latex)",
      nameZh: "医用手套（优先丁腈；避免乳胶）",
      weightG: 12,
      qty: 2,
      category: "health",
      why: "Nitrile preferred; article says to avoid latex due to allergy risk.",
      whyZh: "原文写优先丁腈、避免乳胶过敏风险。",
    },
    {
      name: "CPR face shield / pocket mask",
      nameZh: "CPR 面膜 / 口袋面罩",
      weightG: 28,
      qty: 1,
      category: "health",
      why: "Barrier device if you are trained and need to provide rescue breaths.",
      whyZh: "在已掌握 CPR 技能时提供人工呼吸隔离屏障。",
    },
    {
      name: "Waterproof notepad + pencil or pen",
      nameZh: "防水记事本 + 铅笔或笔",
      weightG: 42,
      qty: 1,
      category: "doc",
      why: "Record vitals, times, meds given—REI links this to small notepad + waterproof writing tools.",
      whyZh: "记录生命体征、时间与用药；原文推荐防水书写工具。",
    },
    {
      name: "Medical waste bag + sharps container",
      nameZh: "医疗垃圾袋 + 锐器盒",
      weightG: 35,
      qty: 1,
      category: "misc",
      why: "Article: waste bag plus box for sharps—safe pack-out of contaminated material.",
      whyZh: "原文写医废袋另加锐器盒，安全收纳与带出污染锐器。",
    },
    {
      name: "Waterproof container for kit & meds",
      nameZh: "防水容器（装药品与耗材）",
      weightG: 95,
      qty: 1,
      category: "misc",
      why: "Keeps dressings dry and organizes meds; explicitly on REI’s tools list.",
      whyZh: "保持敷料干燥、药品有序，原文列在工具补给类。",
    },
    {
      name: "Emergency heat-reflecting blanket",
      nameZh: "应急保温反射毯",
      weightG: 55,
      qty: 1,
      category: "health",
      why: "Listed as emergency essential; can live outside a small kit in your pack.",
      whyZh: "原文作应急必备；也可单独放在包内不必塞进小药盒。",
    },
    {
      name: "Hand sanitizer",
      nameZh: "免洗洗手液",
      weightG: 35,
      qty: 1,
      category: "health",
      why: "Hygiene before eating or after wound care when water is scarce.",
      whyZh: "缺水时进食前后与伤口操作前的手部卫生。",
    },
    {
      name: "Biodegradable soap (small)",
      nameZh: "可降解皂（小包装）",
      weightG: 28,
      qty: 1,
      category: "health",
      why: "REI lists biodegradable soap with other kit hygiene supplies.",
      whyZh: "与手部卫生并列，注意远离水源与最小用量原则。",
    },
  ],
};
