// Curated weight reference library.
// Used to auto-suggest weight when a user adds a custom gear item.
//
// Matching strategy (best-of):
//   1. Brand+model exact match (e.g. "Osprey Atmos 65" → 2160 g)
//   2. Brand only (e.g. "Salomon" trail shoe → ~280 g per shoe = 320 g pair generic)
//   3. Generic noun (e.g. "backpack 55L" → ~1800 g)
//   4. Coarse category fallback (e.g. anything mentioning "shoes" → 700 g)
//
// All matches return both the weight estimate AND a normalized English name so
// "萨洛蒙ultra 4" → "Salomon Ultra 4" (490 g pair).
//
// Library is meant to grow. Easy to extend: append entries below.

import type { Item } from "./packlog-data";

export type WeightHint = {
  // tokens for fuzzy contains-match (case-insensitive)
  tokens: string[];
  weightG: number;
  category: Item["category"];
  // canonical English name to suggest as nameEn
  nameEn?: string;
  // canonical Chinese name to suggest as nameZh
  nameZh?: string;
  // confidence — used purely to break ties when multiple entries match.
  // exact brand+model = 100, brand only = 60, generic = 30, fallback = 10
  weight?: number;
};

/* ============================================================
 * 1) BRAND + MODEL — high-confidence specific products
 * ============================================================ */
const brandModels: WeightHint[] = [
  // Backpacks / Luggage  — bag itself, empty
  {
    tokens: ["osprey atmos 65", "atmos 65"],
    weightG: 2160,
    category: "misc",
    nameEn: "Osprey Atmos AG 65",
    nameZh: "Osprey Atmos AG 65L 登山包",
    weight: 100,
  },
  {
    tokens: ["osprey aether 55", "aether 55"],
    weightG: 2330,
    category: "misc",
    nameEn: "Osprey Aether 55",
    nameZh: "Osprey Aether 55L 登山包",
    weight: 100,
  },
  {
    tokens: ["osprey aether 70", "aether 70"],
    weightG: 2440,
    category: "misc",
    nameEn: "Osprey Aether 70",
    nameZh: "Osprey Aether 70L 登山包",
    weight: 100,
  },
  {
    tokens: ["osprey kestrel 38"],
    weightG: 1500,
    category: "misc",
    nameEn: "Osprey Kestrel 38",
    nameZh: "Osprey Kestrel 38L 背包",
    weight: 100,
  },
  {
    tokens: ["osprey farpoint 40", "farpoint 40"],
    weightG: 1500,
    category: "misc",
    nameEn: "Osprey Farpoint 40",
    nameZh: "Osprey Farpoint 40L 旅行包",
    weight: 100,
  },
  {
    tokens: ["osprey daylite"],
    weightG: 500,
    category: "misc",
    nameEn: "Osprey Daylite",
    nameZh: "Osprey Daylite 日用包",
    weight: 100,
  },
  {
    tokens: ["小鹰 精灵 55", "小鹰精灵 55", "精灵 55", "精灵55"],
    weightG: 1900,
    category: "misc",
    nameEn: "Osprey Ariel 55",
    nameZh: "Osprey 小鹰精灵 55L",
    weight: 100,
  },
  {
    tokens: ["osprey ariel 55", "ariel 55"],
    weightG: 1900,
    category: "misc",
    nameEn: "Osprey Ariel 55",
    nameZh: "Osprey 小鹰精灵 55L",
    weight: 100,
  },
  {
    tokens: ["osprey ariel 65", "ariel 65"],
    weightG: 2010,
    category: "misc",
    nameEn: "Osprey Ariel 65",
    nameZh: "Osprey 小鹰精灵 65L",
    weight: 100,
  },
  {
    tokens: ["deuter aircontact"],
    weightG: 2200,
    category: "misc",
    nameEn: "Deuter Aircontact",
    nameZh: "Deuter 多特登山包",
    weight: 100,
  },
  {
    tokens: ["gregory baltoro 65"],
    weightG: 2240,
    category: "misc",
    nameEn: "Gregory Baltoro 65",
    nameZh: "Gregory 巴托罗 65L",
    weight: 100,
  },
  {
    tokens: ["gregory paragon"],
    weightG: 1840,
    category: "misc",
    nameEn: "Gregory Paragon",
    nameZh: "Gregory Paragon",
    weight: 100,
  },
  {
    tokens: ["mystery ranch"],
    weightG: 1900,
    category: "misc",
    nameEn: "Mystery Ranch Pack",
    nameZh: "神秘农场背包",
    weight: 100,
  },
  {
    tokens: ["arc'teryx beta", "arcteryx beta"],
    weightG: 540,
    category: "apparel",
    nameEn: "Arc'teryx Beta LT Shell",
    nameZh: "始祖鸟 Beta LT 硬壳",
    weight: 100,
  },
  {
    tokens: ["peak design travel backpack 45"],
    weightG: 2050,
    category: "misc",
    nameEn: "Peak Design Travel Backpack 45",
    nameZh: "PD 旅行背包 45L",
    weight: 100,
  },
  {
    tokens: ["peak design everyday 20"],
    weightG: 1500,
    category: "misc",
    nameEn: "Peak Design Everyday 20L",
    nameZh: "PD Everyday 20L",
    weight: 100,
  },

  // Suitcases — typical empty mass
  {
    tokens: ["rimowa essential cabin"],
    weightG: 4300,
    category: "misc",
    nameEn: "Rimowa Essential Cabin",
    nameZh: "Rimowa Essential 登机箱",
    weight: 100,
  },
  {
    tokens: ["rimowa essential check-in", "rimowa check-in"],
    weightG: 4900,
    category: "misc",
    nameEn: "Rimowa Essential Check-In M",
    nameZh: "Rimowa Essential 中型托运箱",
    weight: 100,
  },
  {
    tokens: ["rimowa original"],
    weightG: 4800,
    category: "misc",
    nameEn: "Rimowa Original Cabin",
    nameZh: "Rimowa Original 登机箱",
    weight: 100,
  },
  {
    tokens: ["away bigger carry-on"],
    weightG: 3500,
    category: "misc",
    nameEn: "Away Bigger Carry-On",
    nameZh: "Away Bigger 登机箱",
    weight: 100,
  },
  {
    tokens: ["samsonite cosmolite"],
    weightG: 2800,
    category: "misc",
    nameEn: "Samsonite Cosmolite",
    nameZh: "新秀丽 Cosmolite",
    weight: 100,
  },

  // Trail / Hiking shoes — pair weight
  {
    tokens: ["salomon ultra 4", "salomon speedcross 6", "salomon ultra"],
    weightG: 620,
    category: "apparel",
    nameEn: "Salomon Speedcross 6",
    nameZh: "萨洛蒙 Speedcross 6",
    weight: 90,
  },
  {
    tokens: ["salomon x ultra 4", "x ultra 4"],
    weightG: 760,
    category: "apparel",
    nameEn: "Salomon X Ultra 4",
    nameZh: "萨洛蒙 X Ultra 4 登山鞋",
    weight: 100,
  },
  {
    tokens: ["salomon sense pro"],
    weightG: 480,
    category: "apparel",
    nameEn: "Salomon Sense Pro",
    nameZh: "萨洛蒙 Sense Pro",
    weight: 100,
  },
  {
    tokens: ["salomon s/lab"],
    weightG: 460,
    category: "apparel",
    nameEn: "Salomon S/LAB",
    nameZh: "萨洛蒙 S/LAB 越野跑鞋",
    weight: 100,
  },
  {
    tokens: ["hoka speedgoat"],
    weightG: 600,
    category: "apparel",
    nameEn: "Hoka Speedgoat",
    nameZh: "Hoka Speedgoat",
    weight: 100,
  },
  {
    tokens: ["hoka clifton"],
    weightG: 540,
    category: "apparel",
    nameEn: "Hoka Clifton",
    nameZh: "Hoka Clifton",
    weight: 100,
  },
  {
    tokens: ["la sportiva"],
    weightG: 720,
    category: "apparel",
    nameEn: "La Sportiva Boots",
    nameZh: "拉思珂瑞瓦登山鞋",
    weight: 60,
  },
  {
    tokens: ["scarpa"],
    weightG: 780,
    category: "apparel",
    nameEn: "Scarpa Boots",
    nameZh: "斯卡帕登山鞋",
    weight: 60,
  },
  {
    tokens: ["meindl"],
    weightG: 1100,
    category: "apparel",
    nameEn: "Meindl Boots",
    nameZh: "Meindl 重装登山靴",
    weight: 60,
  },
  {
    tokens: ["sorel caribou"],
    weightG: 1280,
    category: "apparel",
    nameEn: "Sorel Caribou",
    nameZh: "Sorel Caribou 雪地靴",
    weight: 100,
  },
  {
    tokens: ["timberland"],
    weightG: 940,
    category: "apparel",
    nameEn: "Timberland Boots",
    nameZh: "Timberland 工装靴",
    weight: 60,
  },
  {
    tokens: ["nike pegasus"],
    weightG: 580,
    category: "apparel",
    nameEn: "Nike Pegasus",
    nameZh: "Nike Pegasus 跑鞋",
    weight: 100,
  },
  {
    tokens: ["adidas ultraboost"],
    weightG: 620,
    category: "apparel",
    nameEn: "Adidas Ultraboost",
    nameZh: "Adidas Ultraboost 跑鞋",
    weight: 100,
  },
  {
    tokens: ["asics gel"],
    weightG: 540,
    category: "apparel",
    nameEn: "Asics Gel Series",
    nameZh: "亚瑟士 GEL 跑鞋",
    weight: 60,
  },
  {
    tokens: ["birkenstock"],
    weightG: 600,
    category: "apparel",
    nameEn: "Birkenstock Sandals",
    nameZh: "Birkenstock 凉鞋",
    weight: 60,
  },
  {
    tokens: ["teva"],
    weightG: 540,
    category: "apparel",
    nameEn: "Teva Sandals",
    nameZh: "Teva 户外凉鞋",
    weight: 60,
  },

  // Apparel — branded
  {
    tokens: ["arc'teryx atom", "arcteryx atom"],
    weightG: 320,
    category: "apparel",
    nameEn: "Arc'teryx Atom Hoody",
    nameZh: "始祖鸟 Atom 棉服",
    weight: 100,
  },
  {
    tokens: ["patagonia nano puff"],
    weightG: 320,
    category: "apparel",
    nameEn: "Patagonia Nano Puff",
    nameZh: "巴塔哥尼亚 Nano Puff",
    weight: 100,
  },
  {
    tokens: ["patagonia r1"],
    weightG: 360,
    category: "apparel",
    nameEn: "Patagonia R1 Fleece",
    nameZh: "巴塔哥尼亚 R1 抓绒",
    weight: 100,
  },
  {
    tokens: ["mont-bell permafrost", "mont bell"],
    weightG: 720,
    category: "apparel",
    nameEn: "Mont-bell Permafrost Down Parka",
    nameZh: "Mont-bell 羽绒服",
    weight: 100,
  },
  {
    tokens: ["uniqlo ultra light down", "uld"],
    weightG: 220,
    category: "apparel",
    nameEn: "Uniqlo Ultra Light Down",
    nameZh: "优衣库轻型羽绒",
    weight: 100,
  },
  {
    tokens: ["smartwool"],
    weightG: 210,
    category: "apparel",
    nameEn: "Smartwool Merino",
    nameZh: "Smartwool 美利奴",
    weight: 60,
  },
  {
    tokens: ["icebreaker"],
    weightG: 220,
    category: "apparel",
    nameEn: "Icebreaker Merino",
    nameZh: "Icebreaker 美利奴",
    weight: 60,
  },

  // Cameras
  {
    tokens: ["leica q3", "leica q"],
    weightG: 743,
    category: "optic",
    nameEn: "Leica Q3",
    nameZh: "徕卡 Q3",
    weight: 100,
  },
  {
    tokens: ["leica m11", "leica m"],
    weightG: 530,
    category: "optic",
    nameEn: "Leica M11",
    nameZh: "徕卡 M11",
    weight: 100,
  },
  {
    tokens: ["sony a7c", "sony α7c", "α7c"],
    weightG: 514,
    category: "optic",
    nameEn: "Sony α7C",
    nameZh: "索尼 α7C",
    weight: 100,
  },
  {
    tokens: ["sony a7iv", "sony a7 iv"],
    weightG: 658,
    category: "optic",
    nameEn: "Sony α7 IV",
    nameZh: "索尼 α7 IV",
    weight: 100,
  },
  {
    tokens: ["fuji x100v", "x100v", "x100vi", "fuji x100"],
    weightG: 521,
    category: "optic",
    nameEn: "Fuji X100VI",
    nameZh: "富士 X100VI",
    weight: 100,
  },
  {
    tokens: ["fuji xt5", "x-t5"],
    weightG: 557,
    category: "optic",
    nameEn: "Fuji X-T5",
    nameZh: "富士 X-T5",
    weight: 100,
  },
  {
    tokens: ["ricoh gr iii", "ricoh gr3"],
    weightG: 257,
    category: "optic",
    nameEn: "Ricoh GR III",
    nameZh: "理光 GR III",
    weight: 100,
  },
  {
    tokens: ["gopro hero", "gopro"],
    weightG: 153,
    category: "optic",
    nameEn: "GoPro Hero",
    nameZh: "GoPro 运动相机",
    weight: 80,
  },
  {
    tokens: ["dji osmo pocket"],
    weightG: 179,
    category: "optic",
    nameEn: "DJI Osmo Pocket 3",
    nameZh: "DJI Osmo Pocket 3",
    weight: 100,
  },
  {
    tokens: ["dji mini"],
    weightG: 249,
    category: "optic",
    nameEn: "DJI Mini Drone",
    nameZh: "DJI Mini 无人机",
    weight: 80,
  },
  {
    tokens: ["insta360"],
    weightG: 180,
    category: "optic",
    nameEn: "Insta360",
    nameZh: "Insta360 全景相机",
    weight: 80,
  },

  // Tech — branded
  {
    tokens: ["macbook air"],
    weightG: 1240,
    category: "tech",
    nameEn: "MacBook Air",
    nameZh: "MacBook Air",
    weight: 100,
  },
  {
    tokens: ["macbook pro 14"],
    weightG: 1610,
    category: "tech",
    nameEn: "MacBook Pro 14",
    nameZh: "MacBook Pro 14",
    weight: 100,
  },
  {
    tokens: ["macbook pro 16"],
    weightG: 2150,
    category: "tech",
    nameEn: "MacBook Pro 16",
    nameZh: "MacBook Pro 16",
    weight: 100,
  },
  {
    tokens: ["ipad pro"],
    weightG: 580,
    category: "tech",
    nameEn: "iPad Pro",
    nameZh: "iPad Pro",
    weight: 100,
  },
  {
    tokens: ["ipad mini"],
    weightG: 293,
    category: "tech",
    nameEn: "iPad Mini",
    nameZh: "iPad Mini",
    weight: 100,
  },
  {
    tokens: ["airpods pro"],
    weightG: 50,
    category: "tech",
    nameEn: "AirPods Pro",
    nameZh: "AirPods Pro",
    weight: 100,
  },
  {
    tokens: ["airpods max"],
    weightG: 384,
    category: "tech",
    nameEn: "AirPods Max",
    nameZh: "AirPods Max",
    weight: 100,
  },
  {
    tokens: ["sony wh-1000xm", "wh-1000xm5", "wh1000xm"],
    weightG: 250,
    category: "tech",
    nameEn: "Sony WH-1000XM5",
    nameZh: "索尼 WH-1000XM5 降噪耳机",
    weight: 100,
  },
  {
    tokens: ["bose quietcomfort", "bose qc"],
    weightG: 240,
    category: "tech",
    nameEn: "Bose QuietComfort",
    nameZh: "Bose 静音舒适降噪耳机",
    weight: 100,
  },
  {
    tokens: ["anker 737", "anker 737 powerbank"],
    weightG: 630,
    category: "tech",
    nameEn: "Anker 737 Power Bank 24K",
    nameZh: "Anker 737 充电宝 24K",
    weight: 100,
  },
  {
    tokens: ["anker 20000"],
    weightG: 360,
    category: "tech",
    nameEn: "Anker Power Bank 20K",
    nameZh: "Anker 充电宝 20K",
    weight: 100,
  },
  {
    tokens: ["anker 10000"],
    weightG: 220,
    category: "tech",
    nameEn: "Anker Power Bank 10K",
    nameZh: "Anker 充电宝 10K",
    weight: 100,
  },
  {
    tokens: ["kindle oasis"],
    weightG: 188,
    category: "tech",
    nameEn: "Kindle Oasis",
    nameZh: "Kindle Oasis",
    weight: 100,
  },
  {
    tokens: ["kindle paperwhite", "kindle"],
    weightG: 205,
    category: "tech",
    nameEn: "Kindle Paperwhite",
    nameZh: "Kindle Paperwhite",
    weight: 90,
  },
  {
    tokens: ["nintendo switch"],
    weightG: 398,
    category: "tech",
    nameEn: "Nintendo Switch",
    nameZh: "Switch 游戏机",
    weight: 100,
  },
  {
    tokens: ["steam deck"],
    weightG: 670,
    category: "tech",
    nameEn: "Steam Deck",
    nameZh: "Steam Deck",
    weight: 100,
  },
];

/* ============================================================
 * 2) BRAND ONLY — when only brand is recognized
 * ============================================================ */
const brandsOnly: WeightHint[] = [
  {
    tokens: ["arc'teryx", "arcteryx", "始祖鸟"],
    weightG: 540,
    category: "apparel",
    nameEn: "Arc'teryx Apparel",
    weight: 50,
  },
  {
    tokens: ["patagonia", "巴塔哥尼亚"],
    weightG: 380,
    category: "apparel",
    nameEn: "Patagonia Apparel",
    weight: 50,
  },
  {
    tokens: ["the north face", "tnf", "北面"],
    weightG: 520,
    category: "apparel",
    nameEn: "The North Face Apparel",
    weight: 50,
  },
  {
    tokens: ["columbia", "哥伦比亚"],
    weightG: 420,
    category: "apparel",
    nameEn: "Columbia Apparel",
    weight: 50,
  },
  {
    tokens: ["uniqlo", "优衣库"],
    weightG: 240,
    category: "apparel",
    nameEn: "Uniqlo Apparel",
    weight: 50,
  },
  {
    tokens: ["salomon", "萨洛蒙"],
    weightG: 580,
    category: "apparel",
    nameEn: "Salomon Trail Shoes",
    weight: 50,
  },
  {
    tokens: ["merrell", "迈乐"],
    weightG: 820,
    category: "apparel",
    nameEn: "Merrell Boots",
    weight: 50,
  },
  {
    tokens: ["leica", "徕卡"],
    weightG: 680,
    category: "optic",
    nameEn: "Leica Camera",
    weight: 50,
  },
  { tokens: ["sony", "索尼"], weightG: 600, category: "tech", nameEn: "Sony Device", weight: 40 },
  { tokens: ["apple", "苹果"], weightG: 200, category: "tech", nameEn: "Apple Device", weight: 40 },
  {
    tokens: ["anker"],
    weightG: 280,
    category: "tech",
    nameEn: "Anker Charger / Power Bank",
    weight: 50,
  },
  { tokens: ["dji", "大疆"], weightG: 250, category: "optic", nameEn: "DJI Device", weight: 50 },
  {
    tokens: ["osprey", "小鹰"],
    weightG: 1700,
    category: "misc",
    nameEn: "Osprey Backpack",
    weight: 50,
  },
  {
    tokens: ["deuter", "多特"],
    weightG: 1900,
    category: "misc",
    nameEn: "Deuter Backpack",
    weight: 50,
  },
  { tokens: ["gregory"], weightG: 1850, category: "misc", nameEn: "Gregory Backpack", weight: 50 },
  {
    tokens: ["rimowa", "日默瓦"],
    weightG: 4500,
    category: "misc",
    nameEn: "Rimowa Suitcase",
    weight: 50,
  },
];

/* ============================================================
 * 3) GENERIC NOUN — common items without brand
 * ============================================================ */
const generic: WeightHint[] = [
  // Bags & luggage
  {
    tokens: ["登山包", "trekking pack", "hiking pack"],
    weightG: 1800,
    category: "misc",
    nameEn: "Trekking Pack",
    nameZh: "登山包",
    weight: 30,
  },
  {
    tokens: ["backpack", "背包", "リュック"],
    weightG: 900,
    category: "misc",
    nameEn: "Backpack",
    nameZh: "背包",
    weight: 30,
  },
  {
    tokens: ["duffel", "duffle", "驮包"],
    weightG: 900,
    category: "misc",
    nameEn: "Duffel Bag",
    nameZh: "驮包",
    weight: 30,
  },
  {
    tokens: ["suitcase", "luggage", "行李箱", "拉杆箱", "スーツケース"],
    weightG: 4000,
    category: "misc",
    nameEn: "Suitcase",
    nameZh: "行李箱",
    weight: 30,
  },
  {
    tokens: ["carry-on", "carryon", "登机箱"],
    weightG: 3200,
    category: "misc",
    nameEn: "Carry-On",
    nameZh: "登机箱",
    weight: 30,
  },
  {
    tokens: ["sling", "单肩包", "斜挎包"],
    weightG: 420,
    category: "misc",
    nameEn: "Sling Bag",
    nameZh: "单肩包",
    weight: 30,
  },
  {
    tokens: ["tote", "托特包"],
    weightG: 280,
    category: "misc",
    nameEn: "Tote",
    nameZh: "托特包",
    weight: 30,
  },
  {
    tokens: ["dry bag", "防水袋"],
    weightG: 280,
    category: "misc",
    nameEn: "Dry Bag",
    nameZh: "防水袋",
    weight: 30,
  },
  {
    tokens: ["packing cube", "收纳袋"],
    weightG: 90,
    category: "misc",
    nameEn: "Packing Cube",
    nameZh: "收纳袋",
    weight: 30,
  },

  // Apparel
  {
    tokens: ["t-shirt", "tee", "tshirt", "t恤", "tシャツ"],
    weightG: 180,
    category: "apparel",
    nameEn: "T-Shirt",
    nameZh: "T恤",
    weight: 30,
  },
  {
    tokens: ["polo"],
    weightG: 220,
    category: "apparel",
    nameEn: "Polo Shirt",
    nameZh: "Polo 衫",
    weight: 30,
  },
  {
    tokens: ["shirt", "衬衫"],
    weightG: 280,
    category: "apparel",
    nameEn: "Shirt",
    nameZh: "衬衫",
    weight: 25,
  },
  {
    tokens: ["jeans", "denim", "牛仔裤", "ジーンズ"],
    weightG: 620,
    category: "apparel",
    nameEn: "Jeans",
    nameZh: "牛仔裤",
    weight: 30,
  },
  {
    tokens: ["pants", "trousers", "长裤", "ズボン"],
    weightG: 480,
    category: "apparel",
    nameEn: "Pants",
    nameZh: "长裤",
    weight: 25,
  },
  {
    tokens: ["shorts", "短裤"],
    weightG: 220,
    category: "apparel",
    nameEn: "Shorts",
    nameZh: "短裤",
    weight: 30,
  },
  {
    tokens: ["hoodie", "卫衣", "パーカー"],
    weightG: 540,
    category: "apparel",
    nameEn: "Hoodie",
    nameZh: "卫衣",
    weight: 30,
  },
  {
    tokens: ["fleece", "抓绒"],
    weightG: 380,
    category: "apparel",
    nameEn: "Fleece",
    nameZh: "抓绒衣",
    weight: 30,
  },
  {
    tokens: ["down jacket", "down parka", "羽绒服", "羽绒", "ダウン"],
    weightG: 720,
    category: "apparel",
    nameEn: "Down Jacket",
    nameZh: "羽绒服",
    weight: 30,
  },
  {
    tokens: ["puffer", "puffy", "棉服"],
    weightG: 480,
    category: "apparel",
    nameEn: "Puffer Jacket",
    nameZh: "棉服",
    weight: 30,
  },
  {
    tokens: ["shell", "gore-tex", "冲锋衣", "硬壳", "シェル"],
    weightG: 540,
    category: "apparel",
    nameEn: "Hardshell Jacket",
    nameZh: "硬壳冲锋衣",
    weight: 30,
  },
  {
    tokens: ["windbreaker", "wind shell", "风衣"],
    weightG: 180,
    category: "apparel",
    nameEn: "Windbreaker",
    nameZh: "风衣",
    weight: 30,
  },
  {
    tokens: ["rain jacket", "雨衣"],
    weightG: 320,
    category: "apparel",
    nameEn: "Rain Jacket",
    nameZh: "雨衣",
    weight: 30,
  },
  {
    tokens: ["socks", "袜", "ソックス"],
    weightG: 60,
    category: "apparel",
    nameEn: "Socks",
    nameZh: "袜子",
    weight: 30,
  },
  {
    tokens: ["underwear", "内裤", "下着"],
    weightG: 50,
    category: "apparel",
    nameEn: "Underwear",
    nameZh: "内裤",
    weight: 30,
  },
  {
    tokens: ["bra", "文胸", "内衣"],
    weightG: 90,
    category: "apparel",
    nameEn: "Bra",
    nameZh: "内衣",
    weight: 30,
  },
  {
    tokens: ["baselayer", "merino", "美利奴", "打底", "ベースレイヤー"],
    weightG: 210,
    category: "apparel",
    nameEn: "Merino Baselayer",
    nameZh: "美利奴打底",
    weight: 30,
  },
  {
    tokens: ["sweater", "毛衣"],
    weightG: 480,
    category: "apparel",
    nameEn: "Sweater",
    nameZh: "毛衣",
    weight: 30,
  },
  {
    tokens: ["trail shoes", "trail runners", "越野跑鞋"],
    weightG: 620,
    category: "apparel",
    nameEn: "Trail Runners",
    nameZh: "越野跑鞋",
    weight: 35,
  },
  {
    tokens: ["hiking shoes", "hiking boots", "登山鞋", "登山靴"],
    weightG: 980,
    category: "apparel",
    nameEn: "Hiking Boots",
    nameZh: "登山鞋",
    weight: 30,
  },
  {
    tokens: ["sneakers", "运动鞋", "板鞋"],
    weightG: 720,
    category: "apparel",
    nameEn: "Sneakers",
    nameZh: "运动鞋",
    weight: 30,
  },
  {
    tokens: ["running shoes", "跑鞋"],
    weightG: 540,
    category: "apparel",
    nameEn: "Running Shoes",
    nameZh: "跑鞋",
    weight: 30,
  },
  {
    tokens: ["sandals", "凉鞋", "サンダル"],
    weightG: 360,
    category: "apparel",
    nameEn: "Sandals",
    nameZh: "凉鞋",
    weight: 30,
  },
  {
    tokens: ["flip-flops", "人字拖"],
    weightG: 220,
    category: "apparel",
    nameEn: "Flip-flops",
    nameZh: "人字拖",
    weight: 30,
  },
  {
    tokens: ["ski boots", "雪鞋", "雪地靴"],
    weightG: 1280,
    category: "apparel",
    nameEn: "Snow Boots",
    nameZh: "雪地靴",
    weight: 30,
  },
  {
    tokens: ["hat", "cap", "帽", "キャップ"],
    weightG: 90,
    category: "apparel",
    nameEn: "Hat",
    nameZh: "帽子",
    weight: 30,
  },
  {
    tokens: ["beanie", "毛线帽"],
    weightG: 70,
    category: "apparel",
    nameEn: "Beanie",
    nameZh: "毛线帽",
    weight: 30,
  },
  {
    tokens: ["gloves", "手套", "手袋"],
    weightG: 110,
    category: "apparel",
    nameEn: "Gloves",
    nameZh: "手套",
    weight: 30,
  },
  {
    tokens: ["scarf", "围巾", "マフラー"],
    weightG: 140,
    category: "apparel",
    nameEn: "Scarf",
    nameZh: "围巾",
    weight: 30,
  },
  {
    tokens: ["buff", "魔术头巾", "脖套"],
    weightG: 35,
    category: "apparel",
    nameEn: "Buff",
    nameZh: "魔术头巾",
    weight: 30,
  },
  {
    tokens: ["belt", "腰带"],
    weightG: 220,
    category: "apparel",
    nameEn: "Belt",
    nameZh: "腰带",
    weight: 30,
  },
  {
    tokens: ["sunglasses", "墨镜", "太阳镜"],
    weightG: 35,
    category: "apparel",
    nameEn: "Sunglasses",
    nameZh: "墨镜",
    weight: 30,
  },

  // Tech
  {
    tokens: [
      "laptop",
      "macbook",
      "mac book",
      "笔记本电脑",
      "ノートpc",
      "ノートパソコン",
      "电脑",
      "笔电",
      "computer",
      "chromebook",
      "thinkpad",
      "ultrabook",
      "surface laptop",
      "游戏本",
      "轻薄本",
      // In many locales “notebook” means laptop; paper pads use tokens on the doc entry below.
      "notebook",
    ],
    weightG: 1240,
    category: "tech",
    nameEn: "Laptop",
    nameZh: "笔记本电脑",
    weight: 42,
  },
  {
    tokens: ["ipad", "tablet", "平板", "タブレット"],
    weightG: 470,
    category: "tech",
    nameEn: "Tablet",
    nameZh: "平板",
    weight: 30,
  },
  {
    tokens: ["earbuds", "耳机", "イヤホン"],
    weightG: 50,
    category: "tech",
    nameEn: "Earbuds",
    nameZh: "耳机",
    weight: 30,
  },
  {
    tokens: ["headphones", "headphone", "头戴耳机", "ヘッドホン"],
    weightG: 250,
    category: "tech",
    nameEn: "Headphones",
    nameZh: "头戴耳机",
    weight: 30,
  },
  {
    tokens: ["charger", "充电器", "充電器", "adapter", "电源"],
    weightG: 120,
    category: "tech",
    nameEn: "Charger",
    nameZh: "充电器",
    weight: 30,
  },
  {
    tokens: ["adapter", "转换器", "电源转换"],
    weightG: 95,
    category: "tech",
    nameEn: "Travel Adapter",
    nameZh: "电源转换器",
    weight: 30,
  },
  {
    tokens: ["power bank", "powerbank", "充电宝", "モバイルバッテリー"],
    weightG: 360,
    category: "tech",
    nameEn: "Power Bank",
    nameZh: "充电宝",
    weight: 30,
  },
  {
    tokens: ["cable", "线", "ケーブル", "数据线"],
    weightG: 40,
    category: "tech",
    nameEn: "Cable",
    nameZh: "数据线",
    weight: 30,
  },
  {
    tokens: ["mouse", "鼠标", "マウス"],
    weightG: 90,
    category: "tech",
    nameEn: "Mouse",
    nameZh: "鼠标",
    weight: 30,
  },
  {
    tokens: ["keyboard", "键盘"],
    weightG: 480,
    category: "tech",
    nameEn: "Keyboard",
    nameZh: "键盘",
    weight: 30,
  },
  {
    tokens: ["hub", "拓展坞", "扩展坞"],
    weightG: 90,
    category: "tech",
    nameEn: "USB-C Hub",
    nameZh: "拓展坞",
    weight: 30,
  },
  {
    tokens: ["headlamp", "head lamp", "头灯", "ヘッドランプ"],
    weightG: 78,
    category: "tech",
    nameEn: "Headlamp",
    nameZh: "头灯",
    weight: 30,
  },
  {
    tokens: ["watch", "smartwatch", "手表"],
    weightG: 60,
    category: "tech",
    nameEn: "Watch",
    nameZh: "手表",
    weight: 30,
  },

  // Optics / Photo
  {
    tokens: ["camera", "相机", "カメラ"],
    weightG: 600,
    category: "optic",
    nameEn: "Camera",
    nameZh: "相机",
    weight: 30,
  },
  {
    tokens: ["lens", "镜头", "レンズ"],
    weightG: 420,
    category: "optic",
    nameEn: "Lens",
    nameZh: "镜头",
    weight: 30,
  },
  {
    tokens: ["nd filter", "nd滤镜", "ndフィルター"],
    weightG: 38,
    category: "optic",
    nameEn: "ND Filter",
    nameZh: "ND 滤镜",
    weight: 30,
  },
  {
    tokens: ["polarizer", "cpl", "偏振镜"],
    weightG: 38,
    category: "optic",
    nameEn: "CPL Filter",
    nameZh: "偏振镜",
    weight: 30,
  },
  {
    tokens: ["sd card", "sd卡", "sdカード"],
    weightG: 4,
    category: "optic",
    nameEn: "SD Card",
    nameZh: "SD 卡",
    weight: 30,
  },
  {
    tokens: ["tripod", "三脚架", "三脚"],
    weightG: 1100,
    category: "optic",
    nameEn: "Tripod",
    nameZh: "三脚架",
    weight: 30,
  },
  {
    tokens: ["gimbal", "稳定器", "ジンバル"],
    weightG: 410,
    category: "optic",
    nameEn: "Gimbal",
    nameZh: "稳定器",
    weight: 30,
  },
  {
    tokens: ["camera battery", "相机电池", "备用电池"],
    weightG: 86,
    category: "optic",
    nameEn: "Camera Battery",
    nameZh: "相机电池",
    weight: 30,
  },
  {
    tokens: ["lens cloth", "镜头布"],
    weightG: 6,
    category: "optic",
    nameEn: "Lens Cloth",
    nameZh: "镜头布",
    weight: 30,
  },
  {
    tokens: ["binoculars", "望远镜", "双筒"],
    weightG: 720,
    category: "optic",
    nameEn: "Binoculars",
    nameZh: "望远镜",
    weight: 30,
  },
  {
    tokens: ["snorkel mask", "面镜", "潜水镜"],
    weightG: 320,
    category: "optic",
    nameEn: "Snorkel Mask",
    nameZh: "浮潜面镜",
    weight: 30,
  },
  {
    tokens: ["ski goggles", "雪镜", "ゴーグル"],
    weightG: 180,
    category: "optic",
    nameEn: "Ski Goggles",
    nameZh: "雪镜",
    weight: 30,
  },

  // Docs
  {
    tokens: ["passport", "护照", "パスポート"],
    weightG: 60,
    category: "doc",
    nameEn: "Passport",
    nameZh: "护照",
    weight: 30,
  },
  {
    tokens: ["wallet", "钱包", "財布"],
    weightG: 110,
    category: "doc",
    nameEn: "Wallet",
    nameZh: "钱包",
    weight: 30,
  },
  {
    tokens: [
      "spiral notebook",
      "composition notebook",
      "记事本",
      "作业本",
      "日记本",
      "手账本",
      "moleskine",
      "travel journal",
      "field notes",
      "paper notebook",
    ],
    weightG: 220,
    category: "doc",
    nameEn: "Notebook",
    nameZh: "记事本",
    weight: 30,
  },
  {
    tokens: ["pen", "笔", "ペン"],
    weightG: 12,
    category: "doc",
    nameEn: "Pen",
    nameZh: "笔",
    weight: 30,
  },
  {
    tokens: ["visa", "签证"],
    weightG: 8,
    category: "doc",
    nameEn: "Visa",
    nameZh: "签证",
    weight: 30,
  },
  {
    tokens: ["map", "地图"],
    weightG: 120,
    category: "doc",
    nameEn: "Map",
    nameZh: "地图",
    weight: 30,
  },

  // Health
  {
    tokens: ["toothbrush", "牙刷", "歯ブラシ"],
    weightG: 18,
    category: "health",
    nameEn: "Toothbrush",
    nameZh: "牙刷",
    weight: 30,
  },
  {
    tokens: ["toothpaste", "牙膏", "歯磨き粉"],
    weightG: 90,
    category: "health",
    nameEn: "Toothpaste",
    nameZh: "牙膏",
    weight: 30,
  },
  {
    tokens: ["shampoo", "洗发", "シャンプー"],
    weightG: 200,
    category: "health",
    nameEn: "Shampoo",
    nameZh: "洗发水",
    weight: 30,
  },
  {
    tokens: ["conditioner", "护发素"],
    weightG: 200,
    category: "health",
    nameEn: "Conditioner",
    nameZh: "护发素",
    weight: 30,
  },
  {
    tokens: ["body wash", "沐浴露"],
    weightG: 220,
    category: "health",
    nameEn: "Body Wash",
    nameZh: "沐浴露",
    weight: 30,
  },
  {
    tokens: ["sunscreen", "防晒"],
    weightG: 110,
    category: "health",
    nameEn: "Sunscreen",
    nameZh: "防晒霜",
    weight: 30,
  },
  {
    tokens: ["medicine", "药", "薬"],
    weightG: 60,
    category: "health",
    nameEn: "Medicine",
    nameZh: "药品",
    weight: 30,
  },
  {
    tokens: ["mask", "口罩", "マスク"],
    weightG: 4,
    category: "health",
    nameEn: "Mask",
    nameZh: "口罩",
    weight: 30,
  },
  {
    tokens: ["towel", "毛巾", "タオル"],
    weightG: 180,
    category: "health",
    nameEn: "Towel",
    nameZh: "毛巾",
    weight: 30,
  },
  {
    tokens: ["lip balm", "润唇膏"],
    weightG: 12,
    category: "health",
    nameEn: "Lip Balm",
    nameZh: "润唇膏",
    weight: 30,
  },
  {
    tokens: ["razor", "剃须刀"],
    weightG: 80,
    category: "health",
    nameEn: "Razor",
    nameZh: "剃须刀",
    weight: 30,
  },
  {
    tokens: ["deodorant", "止汗剂"],
    weightG: 65,
    category: "health",
    nameEn: "Deodorant",
    nameZh: "止汗剂",
    weight: 30,
  },
  {
    tokens: ["first aid", "急救"],
    weightG: 180,
    category: "health",
    nameEn: "First Aid Kit",
    nameZh: "急救包",
    weight: 30,
  },

  // Misc
  {
    tokens: ["umbrella", "伞", "傘"],
    weightG: 380,
    category: "misc",
    nameEn: "Umbrella",
    nameZh: "雨伞",
    weight: 30,
  },
  {
    tokens: ["water bottle", "水瓶", "水筒", "保温杯"],
    weightG: 280,
    category: "misc",
    nameEn: "Water Bottle",
    nameZh: "水瓶",
    weight: 30,
  },
  {
    tokens: ["soft flask", "软水壶"],
    weightG: 28,
    category: "misc",
    nameEn: "Soft Flask",
    nameZh: "软水壶",
    weight: 30,
  },
  {
    tokens: ["hand warmer", "暖宝", "暖宝宝", "カイロ"],
    weightG: 80,
    category: "misc",
    nameEn: "Hand Warmer",
    nameZh: "暖宝宝",
    weight: 30,
  },
  {
    tokens: ["snacks", "零食", "おやつ"],
    weightG: 150,
    category: "misc",
    nameEn: "Snacks",
    nameZh: "零食",
    weight: 30,
  },
  {
    tokens: ["energy gel", "能量胶"],
    weightG: 32,
    category: "misc",
    nameEn: "Energy Gel",
    nameZh: "能量胶",
    weight: 30,
  },
  {
    tokens: ["book", "书", "本"],
    weightG: 320,
    category: "misc",
    nameEn: "Book",
    nameZh: "书",
    weight: 30,
  },
  {
    tokens: ["sleeping bag", "睡袋"],
    weightG: 720,
    category: "misc",
    nameEn: "Sleeping Bag",
    nameZh: "睡袋",
    weight: 30,
  },
  {
    tokens: ["trekking poles", "登山杖"],
    weightG: 480,
    category: "misc",
    nameEn: "Trekking Poles",
    nameZh: "登山杖",
    weight: 30,
  },
  {
    tokens: ["pillow", "枕"],
    weightG: 240,
    category: "misc",
    nameEn: "Travel Pillow",
    nameZh: "旅行枕",
    weight: 30,
  },
];

/* ============================================================
 * 4) FALLBACK by COARSE CATEGORY KEYWORD
 * ============================================================ */
const coarseFallback: WeightHint[] = [
  {
    tokens: ["jacket", "外套", "上衣"],
    weightG: 540,
    category: "apparel",
    nameEn: "Jacket",
    nameZh: "外套",
    weight: 10,
  },
  {
    tokens: ["shoes", "鞋", "靴"],
    weightG: 720,
    category: "apparel",
    nameEn: "Shoes",
    nameZh: "鞋",
    weight: 10,
  },
  {
    tokens: ["bag", "包", "袋"],
    weightG: 600,
    category: "misc",
    nameEn: "Bag",
    nameZh: "包",
    weight: 10,
  },
];

const allEntries = [...brandModels, ...brandsOnly, ...generic, ...coarseFallback];
export const weightLibrary: WeightHint[] = allEntries;

/**
 * Suggest a weight + category + canonical names from a free-text user input.
 * Returns the highest-confidence match (longer specific tokens win).
 */
export function suggestFromName(name: string): WeightHint | null {
  const q = name.trim().toLowerCase();
  if (!q) return null;
  let best: WeightHint | null = null;
  let bestScore = -1;
  for (const h of allEntries) {
    for (const tok of h.tokens) {
      const t = tok.toLowerCase();
      if (q.includes(t)) {
        // score = base confidence + token length bonus
        const score = (h.weight ?? 30) + t.length;
        if (score > bestScore) {
          best = h;
          bestScore = score;
        }
      }
    }
  }
  return best;
}

// Top-N popular suggestions (for the smart-suggest panel)
export const popularSuggestions: { name: string; hint: WeightHint }[] = [
  { name: "Travel Adapter", hint: { tokens: [], weightG: 95, category: "tech" } },
  { name: "Hand Warmer", hint: { tokens: [], weightG: 80, category: "misc" } },
  { name: "Microfiber Towel", hint: { tokens: [], weightG: 110, category: "health" } },
  { name: "Power Bank 10K", hint: { tokens: [], weightG: 220, category: "tech" } },
  { name: "Sunglasses", hint: { tokens: [], weightG: 35, category: "apparel" } },
  { name: "Reusable Bottle 500ml", hint: { tokens: [], weightG: 280, category: "misc" } },
];
